"use client";
import React, { useState } from "react";
import Link from "next/link";
import { CheckCircle2, Clock, AlertTriangle, Sparkles, Database, ArrowLeftRight, Shield, PartyPopper, ArrowRight } from "lucide-react";

export function DeliverOverview({ role, onSwitchTab, S, MD, modProgress, MC, ProgressBar }) {
  const [showCommit, setShowCommit] = useState(false);
  const [showBack, setShowBack] = useState(false);
  if (role === "offboarder") return <div className="space-y-4"><div className="text-center py-4"><div className="w-12 h-12 rounded-full bg-violet-100 text-violet-700 text-sm font-semibold inline-flex items-center justify-center mx-auto mb-3">{S.initials}</div><h2 className="text-xl font-semibold">{"Thank you, "}<span className="text-violet-600">Minh</span>.</h2><p className="text-[12px] text-gray-500 max-w-xs mx-auto mt-2">{"Your contributions are captured. H\u00e0 Vy will review before committing to the Knowledge Graph."}</p></div><div className="rounded-lg border border-gray-200 bg-white p-4"><p className="text-[11px] font-medium mb-2">What you contributed</p><div className="grid grid-cols-3 gap-3"><MC l="Answered" v={S.answered}/><MC l="Files" v={1}/><MC l="Gaps addressed" v={S.gapsAddressed}/></div></div><div className="rounded-lg border border-gray-200 bg-white p-4"><p className="text-[11px] font-medium mb-2">What happens next</p><div className="space-y-2">{[{n:1,t:"H\u00e0 Vy reviews your contributions",d:"You\u2019ll get a copy of any follow-ups.",active:true},{n:2,t:"Knowledge Graph commit",d:"Your answers will be available to the team in the Knowledge Graph."}].map(s=><div key={s.n} className="flex gap-2.5 text-[11px]"><div className={`w-5 h-5 rounded-full text-[10px] font-medium flex items-center justify-center shrink-0 ${s.active?"bg-violet-100 text-violet-700":"bg-gray-100 text-gray-500"}`}>{s.n}</div><div><p className="font-medium">{s.t}</p><p className="text-gray-500 text-[10px]">{s.d}</p></div></div>)}</div></div></div>;
  if (role === "coworker") return <div className="rounded-lg border border-dashed border-gray-300 bg-gray-50 p-8 text-center"><div className="w-12 h-12 rounded-full bg-gray-100 inline-flex items-center justify-center mb-3 mx-auto"><Clock className="w-5 h-5 text-gray-400" strokeWidth={1.5}/></div><h3 className="text-sm font-medium text-gray-700 mb-1">Session is being finalized</h3><p className="text-xs text-gray-500 max-w-xs mx-auto">{"H\u00e0 Vy is reviewing contributions before committing to the Knowledge Graph."}</p></div>;
  return <div className="space-y-4"><div className="rounded-lg border border-gray-200 bg-white p-5"><h3 className="text-sm font-semibold text-gray-900 mb-3">Session readiness</h3><ProgressBar/><div className="grid grid-cols-4 gap-3 my-3"><MC l="Answered" v={S.answered}/><MC l="Satisfied" v={S.satisfied}/><MC l="Gaps" v={`${S.gapsAddressed}/${S.gaps}`}/><MC l="Files" v={S.files}/></div><div className="pt-3 border-t border-gray-100"><p className="text-[11px] font-medium mb-2">Per-module readiness</p>{MD.flatMap(b=>b.modules).map(m=>{const p=modProgress(m);const tg=m.gaps+(m.moduleGaps||[]).length;const ready=p.answered===p.total&&p.total>0;return <div key={m.name} className="flex items-center gap-2 py-1.5 border-t border-gray-50 text-[11px]"><span className="flex-1 text-gray-900">{m.name}</span><span className="text-gray-500" style={{fontFamily:"ui-monospace,Menlo,monospace"}}>{p.answered}/{p.total}</span><span className="text-gray-400 text-[10px]">{tg}{" gap"}{tg!==1?"s":""}</span>{ready?<span className="text-[9px] px-1.5 py-0.5 rounded bg-emerald-50 text-emerald-700 border border-emerald-200 inline-flex items-center gap-0.5"><CheckCircle2 className="w-2.5 h-2.5"/>Ready</span>:<span className="text-[9px] px-1.5 py-0.5 rounded bg-yellow-50 text-yellow-700 border border-yellow-200 inline-flex items-center gap-0.5"><AlertTriangle className="w-2.5 h-2.5"/>{p.total-p.answered} unanswered</span>}</div>})}</div>{S.questions-S.answered>0&&<div className="mt-3 text-[10px] text-yellow-800 bg-yellow-50 border border-yellow-200 rounded-md px-3 py-2 flex items-center gap-1.5"><AlertTriangle className="w-3 h-3 shrink-0"/>{S.questions-S.answered}{" questions unanswered \u2014 they will not be committed."}</div>}</div><div className="flex items-center gap-3"><button onClick={()=>setShowBack(true)} className="h-9 px-4 rounded-lg border border-gray-300 text-sm font-medium text-gray-700 hover:bg-gray-50 inline-flex items-center gap-1.5"><ArrowLeftRight className="w-3.5 h-3.5"/>Back to Capture</button><button onClick={()=>setShowCommit(true)} className="h-9 px-4 rounded-lg bg-violet-600 hover:bg-violet-700 text-white text-sm font-medium inline-flex items-center gap-2"><Database className="w-3.5 h-3.5"/>Commit to Knowledge Graph</button></div>{showCommit&&<CommitModal S={S} onClose={()=>setShowCommit(false)}/>}{showBack&&<BackModal onClose={()=>setShowBack(false)}/>}</div>;
}

function ConnectedNodes() {
  return (<svg className="mx-auto mb-3 relative" width="132" height="56" viewBox="0 0 132 56" fill="none" aria-hidden="true"><defs><linearGradient id="cn-grad" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stopColor="#34d399"/><stop offset="1" stopColor="#059669"/></linearGradient></defs><line x1="22" y1="28" x2="66" y2="12" stroke="#86efac" strokeWidth="1.5"/><line x1="22" y1="28" x2="66" y2="44" stroke="#86efac" strokeWidth="1.5"/><line x1="66" y1="12" x2="110" y2="28" stroke="#86efac" strokeWidth="1.5"/><line x1="66" y1="44" x2="110" y2="28" stroke="#86efac" strokeWidth="1.5"/><line x1="66" y1="12" x2="66" y2="44" stroke="#86efac" strokeWidth="1.5" strokeDasharray="3,3"/><circle cx="22" cy="28" r="7" fill="url(#cn-grad)"/><circle cx="66" cy="12" r="6" fill="url(#cn-grad)"/><circle cx="66" cy="44" r="6" fill="url(#cn-grad)"/><circle cx="110" cy="28" r="8" fill="url(#cn-grad)"/></svg>);
}
export function CompleteOverview({ role, S, MC }) {
  // OV-04 — Offboarder Complete: thank-you/celebration with connected-nodes header + 3-step timeline (no successor playbook).
  if (role === "offboarder") {
    const steps = [
      { title: "Your answers submitted", desc: `All ${S.questions} questions answered.`, state: "done" },
      { title: "Manager review", desc: "Hà Vy will verify your answers and resolve any gaps.", state: "active" },
      { title: "Committed to Knowledge Graph", desc: "Your knowledge becomes a permanent part of the team’s memory.", state: "upcoming" },
    ];
    return <div className="max-w-lg mx-auto">
      <div className="relative overflow-hidden rounded-xl border border-emerald-200 p-7 text-center mb-5" style={{ background: "linear-gradient(135deg, #f0fdf4 0%, #dcfce7 100%)" }}>
        <ConnectedNodes />
        <h2 className="text-xl font-semibold text-gray-900 mb-1 relative">{"Thank you, Minh Lê"}</h2>
        <p className="text-[13px] text-gray-600 relative">Your knowledge has been preserved.</p>
      </div>
      <div className="grid grid-cols-3 gap-3 mb-5"><MC l="Questions answered" v={S.questions}/><MC l="Modules covered" v={S.modules}/><MC l="Knowledge entries" v={42}/></div>
      <div className="rounded-lg border border-gray-200 bg-white p-5 mb-5"><p className="text-[11px] font-medium text-gray-700 mb-3 uppercase tracking-wider">What happens next</p><div className="space-y-3.5">{steps.map((s, i) => <div key={i} className="flex gap-3"><div className="shrink-0 mt-0.5">{s.state === "done" ? <CheckCircle2 className="w-5 h-5 text-emerald-500" /> : s.state === "active" ? <span className="w-5 h-5 rounded-full bg-violet-100 border-2 border-violet-500 inline-flex items-center justify-center"><span className="w-1.5 h-1.5 rounded-full bg-violet-600" /></span> : <span className="w-5 h-5 rounded-full border-2 border-gray-300 inline-block" />}</div><div><p className={`text-[12px] font-medium ${s.state === "upcoming" ? "text-gray-500" : "text-gray-900"}`}>{s.title}{s.state === "active" && <span className="ml-1.5 text-[9px] px-1.5 py-0.5 rounded bg-violet-50 text-violet-700 border border-violet-200">In progress</span>}</p><p className="text-[11px] text-gray-500 mt-0.5">{s.desc}</p></div></div>)}</div></div>
      <p className="text-[12px] text-gray-500 text-center">Thank you for contributing to the team&apos;s success.</p>
    </div>;
  }
  if (role === "coworker") return <div className="rounded-lg border border-emerald-200 bg-emerald-50/30 p-8 text-center"><div className="w-12 h-12 rounded-full bg-emerald-100 inline-flex items-center justify-center mb-3 mx-auto"><CheckCircle2 className="w-5 h-5 text-emerald-600"/></div><h3 className="text-sm font-medium text-gray-900 mb-1">Session complete</h3><p className="text-xs text-gray-500 max-w-xs mx-auto">{"Minh L\u00ea\u2019s knowledge is now in the Knowledge Graph. The answers you reviewed are available to the team."}</p></div>;
  return <div className="space-y-4"><div className="rounded-md bg-emerald-50 border border-emerald-200 p-3 flex items-center gap-2"><CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0"/><div><p className="text-[12px] font-medium text-emerald-800">Committed to Knowledge Graph</p><p className="text-[10px] text-emerald-600" style={{fontFamily:"ui-monospace,Menlo,monospace"}}>{"Jun 14, 2026 at 3:42 PM \u00b7 487 entries"}</p></div></div><div className="rounded-lg border border-gray-200 bg-white p-5"><div className="grid grid-cols-4 gap-3"><MC l="Committed" v={S.answered}/><MC l="Files" v={S.files}/><MC l="Gaps resolved" v={S.gapsAddressed}/><MC l="Excluded" v={S.questions-S.answered}/></div><p className="text-[11px] text-gray-500 mt-3">{"Minh L\u00ea\u2019s knowledge is now available to the team in the Knowledge Graph."}</p><div className="flex gap-3 mt-3"><Link href={`/knowledge-graph?prompt=${S.id}`} className="h-8 px-3 rounded-md border border-violet-300 text-violet-700 text-xs font-medium inline-flex items-center gap-1.5 hover:bg-violet-50"><Sparkles className="w-3 h-3"/>Explore in Knowledge Graph</Link><Link href="/" className="h-8 px-3 rounded-md border border-gray-300 text-gray-700 text-xs font-medium inline-flex items-center gap-1.5 hover:bg-gray-50">Back to dashboard</Link></div></div></div>;
}

function CommitModal({ S, onClose }) {
  return <div className="fixed inset-0 bg-black/30 z-50 flex items-center justify-center" onClick={onClose}><div className="bg-white rounded-xl shadow-xl p-6 w-[400px] border border-gray-200" onClick={e=>e.stopPropagation()}><h3 className="text-base font-semibold mb-3">Commit to Knowledge Graph</h3><p className="text-[12px] text-gray-500 mb-2">{"You\u2019re about to commit:"}</p><div className="text-[12px] space-y-0.5 mb-3"><p>{"\u00b7 "}{S.answered}{" answers across "}{S.modules}{" knowledge areas"}</p><p>{"\u00b7 "}{S.files}{" files"}</p><p>{"\u00b7 "}{S.gapsAddressed}{" gaps resolved"}</p></div>{S.questions-S.answered>0&&<div className="text-[11px] text-yellow-800 bg-yellow-50 border border-yellow-200 rounded-md px-3 py-2 mb-2">{S.questions-S.answered}{" unanswered questions will be excluded."}</div>}<div className="text-[11px] text-emerald-800 bg-emerald-50 border border-emerald-200 rounded-md px-3 py-2 mb-3 flex items-start gap-1.5"><Shield className="w-3.5 h-3.5 shrink-0 mt-0.5"/><span>Pre-commit sanitization will run automatically. Sensitive content is redacted before anything reaches the graph.</span></div><p className="text-[10px] text-gray-400 mb-4">This action is permanent.</p><div className="flex gap-2 justify-end"><button onClick={onClose} className="h-8 px-3 rounded-md border border-gray-300 text-sm font-medium text-gray-700 hover:bg-gray-50">Cancel</button><button className="h-8 px-3 rounded-md bg-violet-600 text-white text-sm font-medium inline-flex items-center gap-1.5 hover:bg-violet-700"><Database className="w-3.5 h-3.5"/>Commit</button></div></div></div>;
}

function BackModal({ onClose }) {
  return <div className="fixed inset-0 bg-black/30 z-50 flex items-center justify-center" onClick={onClose}><div className="bg-white rounded-xl shadow-xl p-6 w-[380px] border border-gray-200" onClick={e=>e.stopPropagation()}><h3 className="text-base font-semibold mb-3">Reopen Capture?</h3><p className="text-[12px] text-gray-500 mb-2">{"This will reopen the session for Minh L\u00ea. He\u2019ll be notified that more input is needed."}</p><p className="text-[10px] text-gray-400 mb-4">You can move back to Deliver again when ready.</p><div className="flex gap-2 justify-end"><button onClick={onClose} className="h-8 px-3 rounded-md border border-gray-300 text-sm font-medium text-gray-700 hover:bg-gray-50">Cancel</button><button className="h-8 px-3 rounded-md bg-rose-50 border border-rose-300 text-rose-700 text-sm font-medium inline-flex items-center gap-1.5 hover:bg-rose-100"><ArrowLeftRight className="w-3.5 h-3.5"/>Reopen Capture</button></div></div></div>;
}
