"use client";
import React, { useState } from "react";
import Link from "next/link";
import { ChevronLeft, ChevronRight, ArrowRight, X, CheckCircle2, Clock, AlertTriangle, Sparkles, Bell, Layers, User, FileText, ChevronDown, Plus, MessageCircle, Upload, Paperclip } from "lucide-react";
import { DeliverOverview, CompleteOverview } from "./session-deliver";

/* Session Command View — CL-119/120/127/128/129
   Prepare + Capture + Deliver + Complete · 3 roles */

const ROLES = [
  { id: "manager", label: "Hà Vy", sub: "Manager / HR", icon: "HV" },
  { id: "offboarder", label: "Minh Lê", sub: "Offboarder", icon: "ML" },
  { id: "coworker", label: "Coworker", sub: "Project peer", icon: "CW" },
];
const FLOW = [
  { id: "collecting", label: "Collecting data", trigger: "Crawl running — 3 boards." },
  { id: "ready", label: "Ready for review", trigger: "5 modules, 14 questions, 6 gaps." },
  { id: "capture", label: "Capture (active)", trigger: "9 of 14 answered, 7 satisfied." },
  { id: "deliver", label: "Deliver (review)", trigger: "Manager reviewing before KG commit." },
  { id: "complete", label: "Complete", trigger: "Committed to Knowledge Graph." },
];
export const SESSION = {
  name: "Minh Lê", role: "Senior Backend Engineer", dept: "Engineering",
  initials: "ML", daysLeft: 22, deadline: "Jun 30, 2026",
  boards: 3, cards: 64, modules: 5, questions: 14, gaps: 6, coworkers: 3,
  answered: 9, satisfied: 7, gapsAddressed: 4, files: 3,
};
const GQ = [
  { q: "What's the process for handling customer escalations?", from: "Coworker", answer: "On-call engineer first. P1: page lead via PagerDuty. Engineering provides RCA within 24h.", answeredBy: "Minh Lê", answeredAt: "1d ago", satisfiedBy: "Hà Vy", satisfiedAt: "3h" },
  { q: "Are there any undocumented vendor agreements I should know about?", from: "Hà Vy" },
];
export const MODULES_DATA = [
  { board: "Backend Services", boardCards: 34, modules: [
    { name: "Payment Service", cards: 12, qs: 4, gaps: 1, moduleGaps: ["No disaster recovery or failover procedures documented"], items: [
      { name: "Kafka retry configuration", desc: "DLQ routing, backoff strategy, poison message handling. Max 5 retries.", checklist: [{ text: "DLQ routing configured", done: true }, { text: "Backoff documented", done: false }, { text: "Alert on failures", done: false }], gaps: ["Incomplete checklist (2/3 not done)"], gapQs: ["How does the retry logic handle poison messages?"], files: [{ name: "kafka-config.yaml", size: "3.2 KB" }], qs: [
        { q: "How does the retry logic handle poison messages?", from: "AI-generated", answer: "After 5 retries with exponential backoff, messages route to the DLQ. Monitor via Datadog alert #4421.", answeredBy: "Minh Lê", answeredAt: "2h ago", file: { name: "dlq-replay-runbook.pdf", size: "12 KB" }, satisfiedBy: "Coworker A", satisfiedAt: "30m" },
        { q: "Max retry count before DLQ routing?", from: "AI-generated", answer: "Max 5, configurable per topic in kafka-config.yaml. Backoff: 2x from 500ms.", answeredBy: "Minh Lê", answeredAt: "1h ago" },
      ] },
      { name: "Payment gateway timeout", desc: "Circuit breaker pattern, 30s timeout.", checklist: [], gaps: [], files: [], qs: [{ q: "What happens when gateway times out mid-transaction?", from: "AI-generated" }] },
      { name: "Stripe webhook handler", desc: "Payment confirmations and refunds.", checklist: [], gaps: [], files: [], qs: [{ q: "Which webhook events are critical vs optional?", from: "Coworker", answer: "Critical: payment_intent.succeeded, charge.refunded, invoice.payment_failed. Optional → batch queue.", answeredBy: "Minh Lê", answeredAt: "45m", satisfiedBy: "Coworker A", satisfiedAt: "20m" }] },
      { name: "Refund reconciliation", desc: "Nightly Stripe↔ledger reconciliation.", checklist: [], gaps: [], files: [], qs: [] },
      { name: "Currency conversion", desc: "ECB API rates, 04:00 UTC.", checklist: [{ text: "Fallback on API failure", done: true }], gaps: [], files: [], qs: [] },
    ]},
    { name: "CI/CD Pipeline", cards: 8, qs: 3, gaps: 1, moduleGaps: ["Deployment described differently across modules"], items: [
      { name: "Atlas migration rollback", desc: "Migration procedures and rollback.", checklist: [], gaps: ["Missing description"], gapQs: ["Rollback procedure?"], files: [], qs: [{ q: "Rollback procedure for failed Atlas migrations?", from: "Hà Vy", answer: "Run /scripts/atlas-rollback.sh with migration ID. Snapshot before (7d expiry).", answeredBy: "Minh Lê", answeredAt: "4h ago", satisfiedBy: "Hà Vy", satisfiedAt: "2h" }] },
      { name: "GitHub Actions workflow", desc: "lint→test→build→deploy. Node 18/20.", checklist: [{ text: "Staging automated", done: true }, { text: "Prod approval", done: true }], gaps: [], files: [], qs: [{ q: "Runbook for nightly batch failures?", from: "Coworker", answer: "Check Actions logs, rerun transient. 3x fails: check Datadog.", answeredBy: "Minh Lê", answeredAt: "3h ago" }] },
      { name: "Docker image caching", desc: "Layer caching in GHCR.", checklist: [], gaps: [], files: [], qs: [] },
    ]},
    { name: "Shared Libraries", cards: 6, qs: 2, gaps: 0, items: [
      { name: "API key rotation", desc: "90-day rotation via GitHub Action.", checklist: [{ text: "Schedule documented", done: true }, { text: "Auto-rotation on", done: true }], gaps: [], files: [{ name: "api-key-rotation.md", size: "1.8 KB" }], qs: [{ q: "Where is the rotation runbook?", from: "AI-generated", answer: "Wiki: /security/api-key-rotation.md. Ping DevOps on failure.", answeredBy: "Minh Lê", answeredAt: "5h ago", satisfiedBy: "Hà Vy", satisfiedAt: "4h" }] },
      { name: "Logging middleware", desc: "Structured logging + PII redaction.", checklist: [], gaps: [], files: [], qs: [] },
      { name: "Auth token validator", desc: "JWT. RS256 + EdDSA.", checklist: [], gaps: [], files: [], qs: [{ q: "Token refresh strategy?", from: "AI-generated", answer: "15-min access, 7-day refresh HTTP-only cookies. Failure → login.", answeredBy: "Minh Lê", answeredAt: "6h ago", satisfiedBy: "Coworker A", satisfiedAt: "5h" }] },
    ]},
  ]},
  { board: "Platform Infrastructure", boardCards: 18, modules: [
    { name: "Monitoring & Alerts", cards: 10, qs: 3, gaps: 1, moduleGaps: ["SLA commitments undocumented"], items: [
      { name: "Datadog dashboard", desc: "SLO tracking. P50/P95/P99.", checklist: [], gaps: ["Thresholds undocumented"], gapQs: ["Critical alert thresholds?"], files: [], qs: [{ q: "Critical alert thresholds?", from: "AI-generated" }] },
      { name: "PagerDuty escalation", desc: "Primary→secondary→eng mgr.", checklist: [{ text: "Rotation current", done: true }], gaps: [], files: [{ name: "oncall-schedule.pdf", size: "45 KB" }], qs: [] },
      { name: "Log aggregation", desc: "Fluentd→ES→Kibana.", checklist: [], gaps: [], files: [], qs: [{ q: "Log retention policy?", from: "AI-generated" }] },
    ]},
    { name: "Infrastructure as Code", cards: 8, qs: 2, gaps: 0, items: [
      { name: "Terraform modules", desc: "VPC, EKS, RDS. S3+DynamoDB.", checklist: [], gaps: [], files: [], qs: [{ q: "Terraform version pinned?", from: "AI-generated" }] },
      { name: "Helm chart templates", desc: "Deployments + monitoring sidecar.", checklist: [], gaps: [], files: [], qs: [{ q: "Helm overrides per env?", from: "AI-generated" }] },
      { name: "Secrets management", desc: "Vault via sidecar.", checklist: [{ text: "Auto-unseal on", done: true }, { text: "Rotation automated", done: false }], gaps: [], files: [], qs: [] },
    ]},
  ]},
];

function cardStatus(c) { if (!c.qs||c.qs.length===0) return "none"; return c.qs.filter(q=>q.answer).length===c.qs.length?"done":"pending"; }
export function modProgress(m) { if (!m.items) return {total:m.qs,answered:0}; let t=0,a=0; m.items.forEach(c=>c.qs.forEach(q=>{t++;if(q.answer)a++})); return {total:t,answered:a}; }

export default function SessionCommandView({ embedded = false, view = "ready", role: roleProp, step: stepProp, tab: tabProp, chrome = true } = {}) {
  const pinned = !!roleProp;
  const showChrome = chrome && !pinned;
  const [role, setRole] = useState(roleProp || "manager");
  const [stepIdx, setStepIdx] = useState(()=>{const id=stepProp||view;const i=FLOW.findIndex(s=>s.id===id);return i>=0?i:1;});
  const step = FLOW[Math.min(stepIdx,FLOW.length-1)];
  const activeRole = pinned ? roleProp : role;
  if (embedded) return <div>{showChrome&&<PreviewStrip role={role} onRole={setRole} step={step} stepIdx={stepIdx} onJump={setStepIdx}/>}<SessionPage role={activeRole} stepId={step.id} initialTab={tabProp}/></div>;
  return <div className="min-h-screen bg-gray-50 flex flex-col text-gray-900" style={{fontFamily:'ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif'}}><TopBar/>{showChrome&&<PreviewStrip role={role} onRole={setRole} step={step} stepIdx={stepIdx} onJump={setStepIdx}/>}<main className="flex-1"><SessionPage role={activeRole} stepId={step.id} initialTab={tabProp}/></main>{showChrome&&<FooterNav stepIdx={stepIdx} total={FLOW.length} onChange={setStepIdx} trigger={step.trigger}/>}</div>;
}

function SessionPage({ role, stepId, initialTab }) {
  const [activeTab, setActiveTab] = useState(initialTab || "overview");
  const phase = stepId==="capture"?"capture":stepId==="deliver"||stepId==="complete"?"deliver":"prepare";
  const isReady = stepId!=="collecting";
  const tabs = [{id:"overview",label:"Overview"},{id:"data",label:"Data",disabled:role==="offboarder"&&phase==="prepare"},{id:"logs",label:"Logs",hidden:role==="coworker"}];
  return <div className="max-w-5xl mx-auto p-6"><HeroBar phase={phase} stepId={stepId}/><div className="flex gap-0 border-b border-gray-200 mb-5">{tabs.filter(t=>!t.hidden).map(t=><button key={t.id} onClick={()=>!t.disabled&&setActiveTab(t.id)} className={`px-4 py-2.5 text-sm font-medium border-b-2 transition-colors ${activeTab===t.id?"border-violet-600 text-gray-900":t.disabled?"border-transparent text-gray-300 cursor-not-allowed":"border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300"}`}>{t.label}</button>)}</div>{activeTab==="overview"&&<OverviewContent role={role} stepId={stepId} isReady={isReady} onSwitchTab={setActiveTab}/>}{activeTab==="data"&&<DataContent role={role} stepId={stepId} isReady={isReady}/>}{activeTab==="logs"&&<LogsContent role={role} stepId={stepId}/>}</div>;
}

function HeroBar({ phase, stepId }) {
  const cls = {prepare:"bg-blue-50 border-blue-200 text-blue-700",capture:"bg-violet-50 border-violet-200 text-violet-700",deliver:"bg-emerald-50 border-emerald-200 text-emerald-700"};
  const label = stepId==="complete"?"Complete":phase==="prepare"?"Prepare":phase==="capture"?"Capture":"Deliver";
  const metrics = phase==="prepare"?`${SESSION.coworkers} coworkers · ${SESSION.questions} Qs · ${SESSION.gaps} gaps`:phase==="capture"?`${SESSION.answered}/${SESSION.questions} answered · ${SESSION.satisfied} satisfied`:stepId==="complete"?`${SESSION.answered} committed · ${SESSION.files} files`:`${SESSION.answered}/${SESSION.questions} answered · reviewing`;
  return <div className="rounded-lg border border-gray-200 bg-white p-4 mb-5 flex items-center gap-4"><div className={`w-12 h-12 rounded-full ${stepId==="complete"?"bg-emerald-100 text-emerald-700":"bg-violet-100 text-violet-700"} text-sm font-semibold inline-flex items-center justify-center shrink-0`}>{stepId==="complete"?<CheckCircle2 className="w-5 h-5"/>:SESSION.initials}</div><div className="flex-1 min-w-0"><div className="flex items-center gap-2 mb-0.5"><h1 className="text-lg font-semibold text-gray-900">{SESSION.name}&apos;s session</h1><span className={`text-[9px] px-2 py-0.5 rounded uppercase tracking-wider font-semibold border ${cls[phase]}`}>{label}</span></div><p className="text-[12px] text-gray-500">{SESSION.role} · {SESSION.dept}</p><p className="text-[11px] text-gray-500 mt-0.5" style={{fontFamily:"ui-monospace,Menlo,monospace"}}>{stepId!=="complete"?`${SESSION.daysLeft}d left · `:""}{metrics}</p></div></div>;
}

function OverviewContent({ role, stepId, isReady, onSwitchTab }) {
  if (stepId==="complete") return <CompleteOverview role={role} S={SESSION} MC={MC}/>;
  if (stepId==="deliver") return <DeliverOverview role={role} onSwitchTab={onSwitchTab} S={SESSION} MD={MODULES_DATA} modProgress={modProgress} MC={MC} ProgressBar={ProgressBar}/>;
  if (role==="offboarder") return <OffboarderOverview stepId={stepId}/>;
  if (role==="coworker") return <CoworkerOverview stepId={stepId} isReady={isReady} onSwitchTab={onSwitchTab}/>;
  return <ManagerOverview stepId={stepId} isReady={isReady} onSwitchTab={onSwitchTab}/>;
}

function ManagerOverview({ stepId, isReady, onSwitchTab }) {
  if (!isReady) return <div className="rounded-lg border border-gray-200 bg-white p-6 text-center"><div className="w-10 h-10 rounded-full bg-violet-50 inline-flex items-center justify-center mb-3 mx-auto"><div className="w-4 h-4 rounded-full border-2 border-gray-300 border-t-violet-500 animate-spin"/></div><h3 className="text-sm font-medium text-gray-900 mb-1">Collecting data from {SESSION.boards} boards...</h3><p className="text-xs text-gray-500">We&apos;ll notify you when ready.</p></div>;
  if (stepId==="capture") return <div className="space-y-4"><div className="rounded-lg border border-gray-200 bg-white p-5"><h3 className="text-sm font-semibold text-gray-900 mb-3">Capture in progress</h3><ProgressBar/><p className="text-[11px] text-gray-500 mb-4">{SESSION.questions-SESSION.answered} questions remaining</p><div className="grid grid-cols-3 gap-3"><MC l="Satisfied" v={SESSION.satisfied}/><MC l="Waiting review" v={SESSION.answered-SESSION.satisfied}/><MC l="Gaps addressed" v={`${SESSION.gapsAddressed}/${SESSION.gaps}`}/></div><p className="text-[11px] text-gray-500 mt-3" style={{fontFamily:"ui-monospace,Menlo,monospace"}}>Started 3d ago · {SESSION.daysLeft}d left</p></div><div className="flex items-center gap-3"><button onClick={()=>onSwitchTab("data")} className="h-9 px-4 rounded-lg border border-gray-300 text-sm font-medium text-gray-700 hover:bg-gray-50">Review in Data tab</button><button className="h-9 px-4 rounded-lg bg-violet-600 hover:bg-violet-700 text-white text-sm font-medium inline-flex items-center gap-2">Move to Deliver<ArrowRight className="w-3.5 h-3.5"/></button></div></div>;
  return <div className="space-y-4"><div className="rounded-lg border border-gray-200 bg-white p-5"><h3 className="text-sm font-semibold text-gray-900 mb-3">Data collection complete</h3><div className="grid grid-cols-4 gap-3 mb-4"><MC l="Boards" v={SESSION.boards}/><MC l="Cards" v={SESSION.cards}/><MC l="Areas" v={SESSION.modules}/><MC l="Questions" v={SESSION.questions}/></div><div className="pt-3 border-t border-gray-100 space-y-2"><p className="text-[10px] text-gray-500 uppercase tracking-wider font-medium">Knowledge areas</p><div className="flex flex-wrap gap-1.5">{["Payment Service","CI/CD Pipeline","Shared Libraries","Monitoring & Alerts","Infrastructure as Code"].map(m=><span key={m} className="text-[11px] px-2 py-1 rounded-md bg-gray-50 border border-gray-200 text-gray-700">{m}</span>)}</div></div><div className="pt-3 mt-3 border-t border-gray-100 grid grid-cols-2 gap-3"><div><p className="text-[10px] text-gray-500 uppercase tracking-wider font-medium mb-1">Coworker engagement</p><p className="text-[12px] text-gray-700">2 of 3 have asked questions</p></div><div><p className="text-[10px] text-gray-500 uppercase tracking-wider font-medium mb-1">Knowledge gaps</p><p className="text-[12px] text-gray-700">6 gaps (3 card + 3 AI)</p></div></div></div><div className="flex items-center gap-3"><button onClick={()=>onSwitchTab("data")} className="h-9 px-4 rounded-lg border border-gray-300 text-sm font-medium text-gray-700 hover:bg-gray-50">Review in Data tab</button><Link href="/session/minh-le" className="h-9 px-4 rounded-lg bg-violet-600 hover:bg-violet-700 text-white text-sm font-medium inline-flex items-center gap-2">Start Capture<ArrowRight className="w-3.5 h-3.5"/></Link></div></div>;
}

function OffboarderOverview({ stepId }) {
  if (stepId==="capture") return <div className="rounded-lg border border-violet-200 bg-violet-50/30 p-5"><div className="flex items-center gap-2 mb-3"><Sparkles className="w-4 h-4 text-violet-600"/><h3 className="text-sm font-semibold text-gray-900">Your question queue</h3></div><ProgressBar/><p className="text-[12px] text-gray-500 mb-3">{SESSION.questions-SESSION.answered} remaining</p><Link href="/session/minh-le?tab=data" className="h-8 px-4 rounded-md bg-violet-600 hover:bg-violet-700 text-white text-xs font-medium inline-flex items-center gap-1.5">Open question queue<ArrowRight className="w-3 h-3"/></Link></div>;
  return <div className="rounded-lg border border-dashed border-gray-300 bg-gray-50 p-8 text-center"><div className="w-12 h-12 rounded-full bg-gray-100 inline-flex items-center justify-center mb-3 mx-auto"><Clock className="w-5 h-5 text-gray-400" strokeWidth={1.5}/></div><h3 className="text-sm font-medium text-gray-700 mb-1">Your session is being prepared</h3><p className="text-xs text-gray-500">You&apos;ll be notified when ready.</p></div>;
}

function CoworkerOverview({ stepId, isReady, onSwitchTab }) {
  if (!isReady) return <div className="rounded-lg border border-dashed border-gray-300 bg-gray-50 p-8 text-center"><div className="w-12 h-12 rounded-full bg-gray-100 inline-flex items-center justify-center mb-3 mx-auto"><Clock className="w-5 h-5 text-gray-400" strokeWidth={1.5}/></div><h3 className="text-sm font-medium text-gray-700 mb-1">Session is being set up</h3><p className="text-xs text-gray-500">You&apos;ll be notified when ready.</p></div>;
  if (stepId==="capture") return <div className="space-y-4"><div className="rounded-lg border border-gray-200 bg-white p-5"><h3 className="text-sm font-semibold text-gray-900 mb-1">Your questions</h3><p className="text-[12px] text-gray-500 mb-3">Review answers and ask follow-ups.</p><div className="grid grid-cols-3 gap-3"><MC l="Answered" v={2}/><MC l="Waiting" v={1}/><MC l="Satisfied" v={1}/></div><p className="text-[11px] text-yellow-700 mt-3 flex items-center gap-1.5"><AlertTriangle className="w-3 h-3"/>1 answer waiting for review</p></div><button onClick={()=>onSwitchTab("data")} className="h-9 px-4 rounded-lg bg-violet-600 hover:bg-violet-700 text-white text-sm font-medium inline-flex items-center gap-2">Review in Data tab<ArrowRight className="w-3.5 h-3.5"/></button></div>;
  return <div className="space-y-4"><div className="rounded-lg border border-gray-200 bg-white p-5"><h3 className="text-sm font-semibold text-gray-900 mb-1">Minh Lê is leaving soon</h3><p className="text-[12px] text-gray-500 mb-3">Senior Backend Engineer · Last day July 4, 2026</p><div className="pt-3 border-t border-gray-100 space-y-2"><p className="text-[10px] text-gray-500 uppercase tracking-wider font-medium">Knowledge areas</p><div className="flex flex-wrap gap-1.5">{["Payment Service","CI/CD Pipeline","Shared Libraries","Monitoring & Alerts","Infrastructure as Code"].map(m=><span key={m} className="text-[11px] px-2 py-1 rounded-md bg-gray-50 border border-gray-200 text-gray-700">{m}</span>)}</div></div><div className="pt-3 mt-3 border-t border-gray-100 grid grid-cols-2 gap-3"><div><p className="text-[10px] text-gray-500 uppercase tracking-wider font-medium mb-1">Your activity</p><p className="text-[12px] text-gray-700">0 questions asked</p></div><div><p className="text-[10px] text-gray-500 uppercase tracking-wider font-medium mb-1">Others</p><p className="text-[12px] text-gray-700">2 coworkers active</p></div></div></div><button onClick={()=>onSwitchTab("data")} className="h-9 px-4 rounded-lg bg-violet-600 hover:bg-violet-700 text-white text-sm font-medium inline-flex items-center gap-2">Browse Data tab<ArrowRight className="w-3.5 h-3.5"/></button></div>;
}

function DataContent({ role, stepId, isReady }) {
  const [selectedCard, setSelectedCard] = useState(null);
  const isCapture = stepId==="capture"; const isDeliver = stepId==="deliver"||stepId==="complete"; const isComplete = stepId==="complete"; const readOnly = isDeliver;
  if (role==="offboarder"&&!isCapture&&!isDeliver) return <div className="rounded-lg border border-dashed border-gray-300 bg-gray-50 p-8 text-center"><h3 className="text-sm font-medium text-gray-700 mb-1">Questions are being collected</h3><p className="text-xs text-gray-500">You&apos;ll see them when Capture starts.</p></div>;
  if (!isReady) return <div className="rounded-lg border border-dashed border-gray-300 bg-gray-50 p-8 text-center"><div className="w-10 h-10 rounded-full bg-violet-50 inline-flex items-center justify-center mb-3 mx-auto"><div className="w-4 h-4 rounded-full border-2 border-gray-300 border-t-violet-500 animate-spin"/></div><h3 className="text-sm font-medium text-gray-700 mb-1">Data is being collected...</h3></div>;
  const showAnswers = isCapture||isDeliver;
  return <div className="relative"><div>
    {!readOnly&&<div className="mb-4 flex items-center gap-2"><input placeholder="Ask a general question..." className="flex-1 h-9 px-3 rounded-lg border border-gray-200 text-sm focus:outline-none focus:ring-2 focus:ring-violet-500/20"/><button className="h-9 px-3 rounded-lg bg-violet-600 hover:bg-violet-700 text-white text-xs font-medium">Ask</button></div>}
    {GQ.length>0&&<div className="rounded-lg border border-violet-200 bg-violet-50/20 mb-3 overflow-hidden"><div className="px-4 py-2.5 bg-violet-50/40 border-b border-violet-200 flex items-center gap-2"><MessageCircle className="w-3.5 h-3.5 text-violet-500"/><span className="text-sm font-semibold text-gray-900">General questions</span><span className="text-[11px] text-gray-500">{GQ.length}</span></div>{GQ.map((q,i)=><div key={i} className="px-4 py-2.5 border-b border-violet-100 last:border-b-0"><div className="text-[12px] text-gray-900">{q.q}</div><div className="text-[10px] text-gray-500 flex items-center gap-1 mt-0.5"><User className="w-2.5 h-2.5"/>{q.from}</div>{showAnswers&&q.answer&&<AnswerBlock q={q} role={role} committed={isComplete} readOnly={readOnly}/>}{isCapture&&!q.answer&&role==="offboarder"&&<AnswerInput/>}</div>)}</div>}
    {MODULES_DATA.map((board,bi)=><div key={bi} className="rounded-lg border border-gray-200 bg-white mb-3 overflow-hidden"><div className="px-4 py-2.5 bg-gray-50 border-b border-gray-200 flex items-center gap-2"><Layers className="w-3.5 h-3.5 text-gray-400"/><span className="text-sm font-semibold text-gray-900">{board.board}</span><span className="text-[11px] text-gray-500">{board.boardCards}c</span></div>{board.modules.map((mod,mi)=><ModuleSection key={mi} mod={mod} role={role} isCapture={isCapture} isDeliver={isDeliver} isComplete={isComplete} selectedCard={selectedCard} onSelectCard={setSelectedCard}/>)}</div>)}
  </div>{selectedCard&&<><div className="fixed inset-0 bg-black/10 z-30" onClick={()=>setSelectedCard(null)}/><div className="fixed top-0 right-0 h-full w-[480px] bg-white border-l border-gray-200 shadow-xl z-40 overflow-y-auto"><SidePanel card={selectedCard} role={role} onClose={()=>setSelectedCard(null)} isCapture={isCapture} isDeliver={isDeliver} isComplete={isComplete}/></div></>}</div>;
}

function ModuleSection({ mod, role, isCapture, isDeliver, isComplete, selectedCard, onSelectCard }) {
  const [expanded, setExpanded] = useState(true); const [showModQ, setShowModQ] = useState(false);
  const prog = modProgress(mod); const totalGaps = mod.gaps+(mod.moduleGaps||[]).length;
  const showProgress = isCapture||isDeliver; const readOnly = isDeliver;
  return <div className="border-b border-gray-100 last:border-b-0">
    <button onClick={()=>setExpanded(!expanded)} className="w-full px-4 py-2 flex items-center justify-between text-left hover:bg-gray-50"><div className="flex items-center gap-2"><ChevronDown className={`w-3 h-3 text-gray-400 transition-transform ${expanded?"":"-rotate-90"}`}/><span className="text-[13px] font-medium text-gray-900">{mod.name}</span><span className="text-[11px] text-gray-500">{mod.cards}c</span>{mod.qs>0&&<span className="text-[9px] px-1.5 py-0.5 rounded bg-violet-50 text-violet-600 border border-violet-200">{mod.qs}Qs</span>}{totalGaps>0&&<span className="text-[9px] px-1.5 py-0.5 rounded bg-yellow-50 text-yellow-700 border border-yellow-200">{totalGaps}gap{totalGaps>1?"s":""}</span>}{showProgress&&prog.total>0&&<span className={`text-[9px] px-1.5 py-0.5 rounded border ${prog.answered===prog.total?"bg-emerald-50 text-emerald-700 border-emerald-200":"bg-gray-50 text-gray-600 border-gray-200"}`}>{prog.answered}/{prog.total}</span>}</div>{role==="manager"&&!readOnly&&<span className="flex items-center gap-2 text-[10px] text-gray-400"><span className="hover:text-violet-600 inline-flex items-center gap-0.5"><Upload className="w-2.5 h-2.5"/>Upload</span><span className="hover:text-violet-600">Rename</span></span>}</button>
    {expanded&&<>
      {mod.moduleGaps&&mod.moduleGaps.length>0&&<div className="px-4 py-2 pl-10 border-t border-gray-50 space-y-1">{mod.moduleGaps.map((g,gi)=><div key={gi} className="text-[10px] text-yellow-800 bg-yellow-50 border border-yellow-200 rounded-md px-2.5 py-1.5 flex items-start gap-1.5"><Sparkles className="w-3 h-3 shrink-0 mt-0.5 text-yellow-600"/>{g}</div>)}</div>}
      {mod.items&&mod.items.map((card,ci)=>{const isSel=selectedCard?.name===card.name;const st=showProgress?cardStatus(card):null;return <button key={ci} onClick={()=>onSelectCard(card)} className={`w-full px-4 py-2 pl-10 flex items-center gap-2 text-left border-t border-gray-50 ${isSel?"bg-violet-50 border-l-2 border-l-violet-500":"hover:bg-gray-50"}`}>{showProgress&&<span className="w-4 shrink-0 text-center">{st==="done"?<CheckCircle2 className="w-3.5 h-3.5 text-emerald-500"/>:st==="pending"?<span className="text-gray-400 text-[11px]">○</span>:<span className="text-gray-300 text-[11px]">—</span>}</span>}<FileText className="w-3 h-3 text-gray-400 shrink-0"/><span className="text-[12px] text-gray-800 flex-1">{card.name}</span>{card.files&&card.files.length>0&&<Paperclip className="w-2.5 h-2.5 text-gray-300"/>}{card.gaps.length>0&&<span className="text-[8px] px-1 py-0.5 rounded bg-yellow-50 text-yellow-700">gap</span>}{card.qs.length>0&&<span className="text-[8px] px-1 py-0.5 rounded bg-violet-50 text-violet-600">{card.qs.length}Q</span>}</button>})}
      {(!mod.items||mod.items.length===0)&&<div className="px-4 py-2 pl-10 text-[11px] text-gray-400 border-t border-gray-50">{mod.cards} cards</div>}
      {role!=="offboarder"&&!readOnly&&<div className="px-4 py-1.5 pl-10 border-t border-gray-50"><button onClick={e=>{e.stopPropagation();setShowModQ(!showModQ)}} className="text-[10px] text-violet-600 inline-flex items-center gap-1 hover:text-violet-700"><Plus className="w-2.5 h-2.5"/>Ask about this module</button>{showModQ&&<div className="flex gap-1.5 mt-1.5"><input placeholder={`Question about ${mod.name}...`} className="flex-1 h-7 px-2 rounded border border-gray-200 text-[10px] focus:outline-none focus:ring-2 focus:ring-violet-500/20"/><button className="h-7 px-2 rounded bg-violet-600 text-white text-[9px]">Ask</button></div>}</div>}
    </>}
  </div>;
}

function AnswerBlock({ q, role, committed, readOnly }) {
  const [satisfied, setSatisfied] = useState(!!q.satisfiedBy); const [showFU, setShowFU] = useState(false);
  return <div className="mt-2"><div className="rounded-md px-3 py-2 bg-gray-50 border-l-2 border-emerald-400"><p className="text-[10px] text-gray-500 mb-1">{q.answeredBy} · {q.answeredAt}{committed&&<span className="ml-1 text-[8px] px-1 py-0.5 rounded bg-emerald-50 text-emerald-700 border border-emerald-200 inline-flex items-center gap-0.5"><CheckCircle2 className="w-2 h-2"/>Committed</span>}</p><p className="text-[11px] text-gray-800 leading-relaxed">{q.answer}</p>{q.file&&<p className="text-[10px] text-gray-500 mt-1.5 flex items-center gap-1"><Paperclip className="w-2.5 h-2.5"/>{q.file.name} ({q.file.size})</p>}</div>{role!=="offboarder"&&!readOnly&&!committed&&<div className="mt-1.5">{satisfied?<p className="text-[10px] text-emerald-600 flex items-center gap-1"><CheckCircle2 className="w-3 h-3"/>Satisfied by {q.satisfiedBy||"you"} · {q.satisfiedAt||"now"}</p>:<div className="flex items-center gap-2"><button onClick={()=>setSatisfied(true)} className="h-6 px-2 rounded border border-emerald-300 text-emerald-700 text-[10px] inline-flex items-center gap-1 hover:bg-emerald-50"><CheckCircle2 className="w-2.5 h-2.5"/>Mark satisfied</button><button onClick={()=>setShowFU(!showFU)} className="h-6 px-2 rounded border border-gray-300 text-gray-600 text-[10px] inline-flex items-center gap-1 hover:bg-gray-50">Ask follow-up</button></div>}{showFU&&<div className="flex gap-1.5 mt-1.5"><input placeholder="Follow-up..." className="flex-1 h-7 px-2 rounded border border-gray-200 text-[10px] focus:outline-none focus:ring-2 focus:ring-violet-500/20"/><button className="h-7 px-2 rounded bg-violet-600 text-white text-[9px]">Ask</button></div>}</div>}{(readOnly||committed)&&satisfied&&<p className="mt-1 text-[10px] text-emerald-600 flex items-center gap-1"><CheckCircle2 className="w-3 h-3"/>Satisfied by {q.satisfiedBy} · {q.satisfiedAt}</p>}</div>;
}

function AnswerInput() { return <div className="mt-2"><textarea placeholder="Type your answer..." className="w-full h-16 px-2 py-1.5 rounded border border-gray-200 text-[11px] resize-none focus:outline-none focus:ring-2 focus:ring-violet-500/20"/><div className="flex items-center justify-between mt-1"><button className="text-[10px] text-gray-500 inline-flex items-center gap-1 hover:text-violet-600"><Paperclip className="w-2.5 h-2.5"/>Attach file</button><button className="h-6 px-2 rounded bg-violet-600 text-white text-[10px]">Submit</button></div></div>; }

function SidePanel({ card, role, onClose, isCapture, isDeliver, isComplete }) {
  const [followUp, setFollowUp] = useState(""); const showAnswers = isCapture||isDeliver; const readOnly = isDeliver;
  return <div className="p-5">
    <div className="flex items-center justify-between mb-3"><h3 className="text-[15px] font-semibold text-gray-900">{card.name}</h3><button onClick={onClose} className="w-7 h-7 rounded-md hover:bg-gray-100 inline-flex items-center justify-center text-gray-400"><X className="w-4 h-4"/></button></div>
    <p className="text-[10px] text-gray-500 uppercase tracking-wider font-medium mt-3 mb-1 pt-2 border-t border-gray-100">Description</p><p className="text-[11px] text-gray-700 leading-relaxed mb-2">{card.desc}</p>
    {card.checklist.length>0&&<><p className="text-[10px] text-gray-500 uppercase tracking-wider font-medium mt-3 mb-1 pt-2 border-t border-gray-100">Checklist</p>{card.checklist.map((c,i)=><div key={i} className="flex items-center gap-1.5 text-[11px] py-0.5">{c.done?<CheckCircle2 className="w-3 h-3 text-emerald-500"/>:<div className="w-3 h-3 rounded border border-gray-300"/>}<span className={c.done?"text-gray-500 line-through":"text-gray-700"}>{c.text}</span></div>)}</>}
    {card.gaps.length>0&&<><p className="text-[10px] text-gray-500 uppercase tracking-wider font-medium mt-3 mb-1 pt-2 border-t border-gray-100">Gaps ({card.gaps.length})</p>{card.gaps.map((g,i)=><div key={i} className="text-[10px] text-yellow-800 bg-yellow-50 border border-yellow-200 rounded-md px-2.5 py-1.5 mb-1"><div className="flex items-start gap-1.5"><AlertTriangle className="w-3 h-3 shrink-0 mt-0.5"/>{g}</div>{card.gapQs&&card.gapQs[i]&&<p className="text-[9px] text-violet-600 mt-1 pl-4">Related Q: {card.gapQs[i]}</p>}</div>)}</>}
    <p className="text-[10px] text-gray-500 uppercase tracking-wider font-medium mt-3 mb-1 pt-2 border-t border-gray-100">Files ({(card.files||[]).length})</p>
    {(card.files||[]).length>0?(card.files||[]).map((f,i)=><div key={i} className="flex items-center gap-2 text-[11px] py-1.5 px-2.5 rounded-md bg-gray-50 mb-1"><Paperclip className="w-3 h-3 text-gray-400 shrink-0"/><span className="text-gray-800 flex-1">{f.name}</span><span className="text-[10px] text-gray-400">{f.size}</span></div>):<p className="text-[11px] text-gray-400 mb-1">No files yet</p>}
    {role!=="offboarder"&&!readOnly&&<button className="text-[10px] text-violet-600 inline-flex items-center gap-1 mt-1 hover:text-violet-700"><Upload className="w-2.5 h-2.5"/>Upload file</button>}
    <p className="text-[10px] text-gray-500 uppercase tracking-wider font-medium mt-3 mb-1 pt-2 border-t border-gray-100">Questions ({card.qs.length})</p>
    {card.qs.length>0?card.qs.map((q,i)=><div key={i} className="text-[11px] bg-gray-50 rounded-md px-2.5 py-2 mb-1.5"><p className="text-gray-900 mb-0.5">{q.q}</p><p className="text-[10px] text-gray-500 flex items-center gap-1">{q.from==="AI-generated"?<><Sparkles className="w-2.5 h-2.5 text-violet-500"/>{q.from}</>:<><User className="w-2.5 h-2.5"/>{q.from}</>}</p>{showAnswers&&q.answer&&<AnswerBlock q={q} role={role} committed={isComplete} readOnly={readOnly}/>}{isCapture&&!q.answer&&role==="offboarder"&&<AnswerInput/>}</div>):<p className="text-[11px] text-gray-400 mb-1">No questions yet</p>}
    {role!=="offboarder"&&!readOnly&&<><p className="text-[10px] text-gray-500 uppercase tracking-wider font-medium mt-3 mb-1 pt-2 border-t border-gray-100">Ask a question</p><div className="flex gap-1.5"><input value={followUp} onChange={e=>setFollowUp(e.target.value)} placeholder="Your question..." className="flex-1 h-8 px-2.5 rounded-md border border-gray-200 text-[11px] focus:outline-none focus:ring-2 focus:ring-violet-500/20"/><button className="h-8 px-2.5 rounded-md bg-violet-600 text-white text-[10px] font-medium">Ask</button></div></>}
  </div>;
}

function LogsContent({ role, stepId }) {
  if (stepId==="collecting"||(role==="offboarder"&&stepId==="ready")) return <div className="text-center py-8 text-sm text-gray-500">No activity yet</div>;
  const logs = [
    ...(stepId==="complete"?[{ts:"3:42 PM",type:"system",text:"Hà Vy committed to Knowledge Graph — 9 answers, 3 files",accent:"#5DCAA5"}]:[]),
    ...(stepId==="deliver"||stepId==="complete"?[{ts:"2:30 PM",type:"system",text:"Hà Vy moved session to Deliver"}]:[]),
    ...(["capture","deliver","complete"].includes(stepId)?[
      {ts:"2:15 PM",type:"questions",text:"Minh Lê answered about token refresh"},
      {ts:"1:40 PM",type:"questions",text:"Coworker A marked satisfied: webhook events"},
      {ts:"1:20 PM",type:"files",text:"Minh Lê attached dlq-replay-runbook.pdf"},
      {ts:"12:50 PM",type:"questions",text:"Minh Lê answered about retry logic"},
      {ts:"11:05 AM",type:"system",text:"Capture started — Minh Lê notified"},
    ]:[]),
    {ts:"10:45 AM",type:"questions",text:"Coworker asked about escalations"},
    {ts:"10:32 AM",type:"system",text:"Crawl complete — 64 cards, 5 modules"},
    {ts:"10:24 AM",type:"system",text:"Session created by Hà Vy"},
  ];
  return <div className="space-y-1.5"><div className="flex gap-2 mb-3">{["All","System","Questions","Files","Edits"].map(f=><button key={f} className={`px-2.5 py-1 rounded-md text-[11px] ${f==="All"?"bg-violet-50 text-violet-700 font-medium":"text-gray-500 hover:bg-gray-100"}`}>{f}</button>)}</div>{logs.map((l,i)=>{const border=l.accent||(l.type==="system"?"rgb(229,231,235)":l.type==="questions"?"rgb(124,58,237)":"rgb(234,179,8)");return <div key={i} className="flex items-start gap-3 px-3 py-2 rounded-md border border-gray-200 bg-white" style={{borderLeft:`2px solid ${border}`}}><span className="text-[10px] text-gray-500 shrink-0 mt-0.5" style={{fontFamily:"ui-monospace,Menlo,monospace"}}>{l.ts}</span><span className={`text-[9px] px-1.5 py-0.5 rounded uppercase tracking-wider font-medium shrink-0 ${l.type==="questions"?"bg-violet-50 text-violet-600":l.type==="files"?"bg-yellow-50 text-yellow-700":"bg-gray-100 text-gray-500"}`}>{l.type}</span><span className="text-[11px] text-gray-900">{l.text}</span></div>})}</div>;
}

export function ProgressBar() { return <div className="flex items-center gap-3 mb-1"><div className="flex-1 h-[6px] rounded-full bg-gray-200 overflow-hidden"><div className="h-full rounded-full bg-violet-500" style={{width:`${Math.round(SESSION.answered/SESSION.questions*100)}%`}}/></div><span className="text-[11px] text-gray-700 font-medium" style={{fontFamily:"ui-monospace,Menlo,monospace"}}>{SESSION.answered}/{SESSION.questions}</span></div>; }
export function MC({ l, v }) { return <div className="rounded-md bg-gray-50 border border-gray-200 px-3 py-2"><div className="text-[9px] text-gray-500 uppercase tracking-wider font-medium">{l}</div><div className="text-lg font-semibold text-gray-900 mt-0.5" style={{fontFamily:"ui-monospace,Menlo,monospace"}}>{v}</div></div>; }
function PreviewStrip({ role, onRole, step, stepIdx, onJump }) { return <div className="bg-slate-900 text-slate-200 px-5 py-2 flex items-center gap-3 flex-wrap"><span className="text-[10px] tracking-[0.16em] font-semibold text-slate-400" style={{fontFamily:"ui-monospace,Menlo,monospace"}}>PREVIEW</span><span className="text-slate-600">·</span><div className="flex items-center gap-1">{ROLES.map(r=><button key={r.id} onClick={()=>onRole(r.id)} className={`h-7 px-2.5 rounded-md text-[12px] border ${role===r.id?"bg-violet-600 text-white border-violet-600":"bg-slate-800 text-slate-300 border-slate-700 hover:border-slate-500"}`}>{r.label}<span className="opacity-60 ml-1">· {r.sub}</span></button>)}</div><span className="text-slate-600">·</span><div className="flex items-center gap-1.5"><span className="text-[11px] text-slate-400" style={{fontFamily:"ui-monospace,Menlo,monospace"}}>step {stepIdx+1}/{FLOW.length}</span><div className="flex items-center gap-1">{FLOW.map((s,i)=><button key={s.id} title={s.label} onClick={()=>onJump(i)} className={`w-7 h-7 rounded-md text-[11px] border ${i===stepIdx?"bg-violet-600 text-white border-violet-600":"bg-slate-800 text-slate-300 border-slate-700 hover:border-slate-500"}`} style={{fontFamily:"ui-monospace,Menlo,monospace"}}>{i+1}</button>)}</div></div><span className="ml-auto text-[11px] text-slate-400 truncate">{step.label}</span></div>; }
function TopBar() { return <header className="bg-white border-b border-gray-200 px-5 py-2.5 flex items-center justify-between gap-4"><div className="flex items-center gap-2 shrink-0"><div className="w-1.5 h-1.5 bg-violet-500 rounded-full"/><span className="text-gray-900 font-semibold tracking-[0.18em] text-xs" style={{fontFamily:"ui-monospace,Menlo,monospace"}}>ART-EEP</span></div><div className="flex items-center gap-3"><button className="h-8 w-8 rounded-md hover:bg-gray-100 inline-flex items-center justify-center text-gray-500 relative"><Bell className="w-3.5 h-3.5" strokeWidth={1.75}/><span className="absolute top-1 right-1 w-1.5 h-1.5 rounded-full bg-rose-500"/></button><div className="flex items-center gap-2 pl-2 border-l border-gray-200"><div className="w-7 h-7 rounded-full bg-violet-100 text-violet-700 text-[11px] font-semibold inline-flex items-center justify-center">HV</div><div className="text-[11px]"><div className="font-medium text-gray-900 leading-tight">Hà Vy</div><div className="text-gray-500 leading-tight">Manager</div></div></div></div></header>; }
function FooterNav({ stepIdx, total, onChange, trigger }) { const atFirst=stepIdx===0,atLast=stepIdx===total-1; return <footer className="bg-white border-t border-gray-200 px-5 py-2.5 flex items-center justify-between sticky bottom-0 z-20"><button onClick={()=>!atFirst&&onChange(stepIdx-1)} disabled={atFirst} className={`h-8 px-3 rounded-md text-sm font-medium inline-flex items-center gap-1.5 focus:outline-none focus:ring-2 focus:ring-violet-500/20 ${atFirst?"text-gray-300 cursor-not-allowed":"text-gray-700 hover:bg-gray-100"}`}><ChevronLeft className="w-3.5 h-3.5"/>Prev</button><div className="hidden sm:block text-[11px] text-gray-500 max-w-md text-center truncate px-3">{trigger}</div><button onClick={()=>!atLast&&onChange(stepIdx+1)} disabled={atLast} className={`h-8 px-3 rounded-md text-sm font-medium inline-flex items-center gap-1.5 focus:outline-none focus:ring-2 focus:ring-violet-500/30 ${atLast?"bg-gray-100 text-gray-400 cursor-not-allowed":"bg-violet-600 hover:bg-violet-700 text-white"}`}>Next<ChevronRight className="w-3.5 h-3.5"/></button></footer>; }
