"use client";

import React, { useState } from "react";
import Link from "next/link";
import {
  ChevronLeft, ChevronRight, ArrowRight, X,
  CheckCircle2, Clock, AlertTriangle, Sparkles,
  Bell, Layers, User, Users, FileText,
  ChevronDown, Plus, Search, MessageCircle, Upload, Paperclip
} from "lucide-react";

/* ═══ Session Command View — CL-119/120/127/128 ═══
   Prepare + Capture · 3 roles · Right drawer Side Panel
   Gaps = signals → generate questions (gap→Q link shown) */

const ROLES = [
  { id: "manager", label: "Hà Vy", sub: "Manager / HR", icon: "HV" },
  { id: "offboarder", label: "Minh Lê", sub: "Offboarder", icon: "ML" },
  { id: "coworker", label: "Coworker", sub: "Project peer", icon: "CW" },
];

const FLOW = [
  { id: "collecting", label: "Collecting data", trigger: "Crawl running — 3 boards being processed." },
  { id: "ready", label: "Ready for review", trigger: "Crawl done. 5 modules, 14 questions, 6 gaps." },
  { id: "capture", label: "Capture (active)", trigger: "Offboarder answering. 9 of 14 done, 7 satisfied." },
];

const SESSION = {
  name: "Minh Lê", role: "Senior Backend Engineer", dept: "Engineering",
  initials: "ML", daysLeft: 22, deadline: "Jun 30, 2026",
  boards: 3, cards: 64, modules: 5, questions: 14, gaps: 6, coworkers: 3,
  answered: 9, satisfied: 7, gapsAddressed: 4,
};

const GENERAL_QUESTIONS = [
  { q: "What's the process for handling customer escalations?", from: "Coworker", answer: "On-call engineer first. P1: page lead via PagerDuty. Engineering provides RCA within 24h.", answeredBy: "Minh Lê", answeredAt: "1d ago", satisfiedBy: "Hà Vy", satisfiedAt: "3h" },
  { q: "Are there any undocumented vendor agreements I should know about?", from: "Hà Vy" },
];

const MODULES_DATA = [
  { board: "Backend Services", boardCards: 34, modules: [
    { name: "Payment Service", cards: 12, qs: 4, gaps: 1, moduleGaps: ["No disaster recovery or failover procedures documented"], items: [
      { name: "Kafka retry configuration", desc: "Kafka consumer retry config: DLQ routing, backoff strategy, poison message handling. Exponential backoff, max 5 retries.", checklist: [{ text: "DLQ routing configured", done: true }, { text: "Backoff strategy documented", done: false }, { text: "Alert on repeated failures", done: false }], gaps: ["Incomplete checklist (2/3 not done)"], gapQs: ["How does the retry logic handle poison messages?"], files: [{ name: "kafka-config.yaml", size: "3.2 KB" }], qs: [
        { q: "How does the retry logic handle poison messages?", from: "AI-generated", answer: "After 5 retries with exponential backoff, messages route to the DLQ. Monitor DLQ depth via Datadog alert #4421. See attached runbook for manual replay.", answeredBy: "Minh Lê", answeredAt: "2h ago", file: { name: "dlq-replay-runbook.pdf", size: "12 KB" }, satisfiedBy: "Coworker A", satisfiedAt: "30m ago" },
        { q: "What's the max retry count before DLQ routing?", from: "AI-generated", answer: "Max 5 retries, configurable per topic in kafka-config.yaml. Backoff: 2x from 500ms.", answeredBy: "Minh Lê", answeredAt: "1h ago" },
      ] },
      { name: "Payment gateway timeout", desc: "Payment gateway timeout and fallback. Circuit breaker pattern, 30s timeout.", checklist: [], gaps: [], files: [], qs: [{ q: "What happens when the gateway times out mid-transaction?", from: "AI-generated" }] },
      { name: "Stripe webhook handler", desc: "Stripe webhook handler for payment confirmations and refunds.", checklist: [], gaps: [], files: [], qs: [{ q: "Which webhook events are critical vs optional?", from: "Coworker", answer: "Critical: payment_intent.succeeded, charge.refunded, invoice.payment_failed. Optional events go to batch queue.", answeredBy: "Minh Lê", answeredAt: "45m ago", satisfiedBy: "Coworker A", satisfiedAt: "20m ago" }] },
      { name: "Refund reconciliation job", desc: "Nightly batch reconciling refund records between Stripe and internal ledger.", checklist: [], gaps: [], files: [], qs: [] },
      { name: "Currency conversion rates", desc: "Daily exchange rates from ECB API, refreshes 04:00 UTC.", checklist: [{ text: "Fallback to previous rate on API failure", done: true }], gaps: [], files: [], qs: [] },
    ]},
    { name: "CI/CD Pipeline", cards: 8, qs: 3, gaps: 1, moduleGaps: ["Deployment process described differently across modules"], items: [
      { name: "Atlas migration rollback", desc: "Atlas migration procedures and rollback steps.", checklist: [], gaps: ["Missing description"], gapQs: ["What's the rollback procedure for failed Atlas migrations?"], files: [], qs: [{ q: "What's the rollback procedure for failed Atlas migrations?", from: "Hà Vy", answer: "Run /scripts/atlas-rollback.sh with migration ID. Always snapshot before migrations (auto-expire 7 days).", answeredBy: "Minh Lê", answeredAt: "4h ago", satisfiedBy: "Hà Vy", satisfiedAt: "2h" }] },
      { name: "GitHub Actions workflow", desc: "CI workflow: lint→test→build→deploy. Matrix strategy Node 18/20.", checklist: [{ text: "Staging deploy automated", done: true }, { text: "Prod deploy requires approval", done: true }], gaps: [], files: [], qs: [{ q: "Is there a runbook for the nightly batch job failures?", from: "Coworker", answer: "Check Actions logs, rerun transient failures. 3x fails: check Datadog.", answeredBy: "Minh Lê", answeredAt: "3h ago" }] },
      { name: "Docker image caching", desc: "Docker layer caching. Cache in GitHub Container Registry.", checklist: [], gaps: [], files: [], qs: [] },
    ]},
    { name: "Shared Libraries", cards: 6, qs: 2, gaps: 0, items: [
      { name: "API key rotation", desc: "API key rotation every 90 days via GitHub Action.", checklist: [{ text: "Rotation schedule documented", done: true }, { text: "Auto-rotation configured", done: true }], gaps: [], files: [{ name: "api-key-rotation.md", size: "1.8 KB" }], qs: [{ q: "Where is the API key rotation runbook?", from: "AI-generated", answer: "Wiki: /security/api-key-rotation.md. Ping DevOps on failure.", answeredBy: "Minh Lê", answeredAt: "5h ago", satisfiedBy: "Hà Vy", satisfiedAt: "4h" }] },
      { name: "Logging middleware", desc: "Express middleware for structured logging with PII redaction.", checklist: [], gaps: [], files: [], qs: [] },
      { name: "Auth token validator", desc: "JWT validation library. Supports RS256 and EdDSA.", checklist: [], gaps: [], files: [], qs: [{ q: "What's the token refresh strategy?", from: "AI-generated", answer: "15-min access tokens, 7-day refresh in HTTP-only cookies. On failure, redirect to login.", answeredBy: "Minh Lê", answeredAt: "6h ago", satisfiedBy: "Coworker A", satisfiedAt: "5h" }] },
    ]},
  ]},
  { board: "Platform Infrastructure", boardCards: 18, modules: [
    { name: "Monitoring & Alerts", cards: 10, qs: 3, gaps: 1, moduleGaps: ["SLA commitments for alert thresholds undocumented"], items: [
      { name: "Datadog dashboard setup", desc: "Service health dashboard with SLO tracking. P50/P95/P99 latency.", checklist: [], gaps: ["Alert thresholds undocumented"], gapQs: ["What are the critical alert thresholds?"], files: [], qs: [{ q: "What are the critical alert thresholds?", from: "AI-generated" }] },
      { name: "PagerDuty escalation policy", desc: "On-call rotation: primary→secondary→eng manager.", checklist: [{ text: "Rotation schedule current", done: true }], gaps: [], files: [{ name: "oncall-schedule.pdf", size: "45 KB" }], qs: [] },
      { name: "Log aggregation pipeline", desc: "Fluentd→Elasticsearch→Kibana centralized logging.", checklist: [], gaps: [], files: [], qs: [{ q: "What's the log retention policy?", from: "AI-generated" }] },
    ]},
    { name: "Infrastructure as Code", cards: 8, qs: 2, gaps: 0, items: [
      { name: "Terraform modules", desc: "Terraform modules for VPC, EKS, RDS. S3 state with DynamoDB locking.", checklist: [], gaps: [], files: [], qs: [{ q: "Which Terraform version and providers are pinned?", from: "AI-generated" }] },
      { name: "Helm chart templates", desc: "Helm charts for service deployments with monitoring sidecar.", checklist: [], gaps: [], files: [], qs: [{ q: "How do we handle Helm value overrides per environment?", from: "AI-generated" }] },
      { name: "Secrets management", desc: "Vault integration for runtime secrets via sidecar injector.", checklist: [{ text: "Vault auto-unseal configured", done: true }, { text: "Secret rotation automated", done: false }], gaps: [], files: [], qs: [] },
    ]},
  ]},
];

function cardStatus(card) { if (!card.qs || card.qs.length === 0) return "none"; return card.qs.filter(q => q.answer).length === card.qs.length ? "done" : "pending"; }
function modProgress(mod) { if (!mod.items || mod.items.length === 0) return { total: mod.qs, answered: 0 }; let t = 0, a = 0; mod.items.forEach(c => { c.qs.forEach(q => { t++; if (q.answer) a++; }); }); return { total: t, answered: a }; }

export default function SessionCommandView({ embedded = false, view = "ready" } = {}) {
  const [role, setRole] = useState("manager");
  const [stepIdx, setStepIdx] = useState(() => { const i = FLOW.findIndex(s => s.id === view); return i >= 0 ? i : 1; });
  const step = FLOW[Math.min(stepIdx, FLOW.length - 1)];
  const handleRoleChange = (r) => { setRole(r); setStepIdx(role === "manager" ? stepIdx : Math.min(stepIdx, 1)); };
  if (embedded) { return (<div><RoleTabBar role={role} onChange={handleRoleChange} /><FlowBar step={step} stepIdx={Math.min(stepIdx, FLOW.length - 1)} onJump={setStepIdx} roleLabel={ROLES.find(r => r.id === role)?.sub} /><SessionPage role={role} stepId={step.id} /></div>); }
  return (<div className="min-h-screen bg-gray-50 flex flex-col text-gray-900" style={{ fontFamily: 'ui-sans-serif, system-ui, -apple-system, "Segoe UI", sans-serif' }}><TopBar /><RoleTabBar role={role} onChange={handleRoleChange} /><FlowBar step={step} stepIdx={Math.min(stepIdx, FLOW.length - 1)} onJump={setStepIdx} roleLabel={ROLES.find(r => r.id === role)?.sub} /><main className="flex-1"><SessionPage role={role} stepId={step.id} /></main><FooterNav stepIdx={Math.min(stepIdx, FLOW.length - 1)} total={FLOW.length} onChange={setStepIdx} trigger={step.trigger} /></div>);
}

function SessionPage({ role, stepId }) {
  const [activeTab, setActiveTab] = useState("overview");
  const phase = stepId === "capture" ? "capture" : "prepare";
  const isReady = stepId === "ready" || stepId === "capture";
  const tabs = [{ id: "overview", label: "Overview" }, { id: "data", label: "Data", disabled: role === "offboarder" && phase === "prepare" }, { id: "logs", label: "Logs", hidden: role === "coworker" }];
  return (<div className="max-w-5xl mx-auto p-6"><HeroBar phase={phase} /><div className="flex gap-0 border-b border-gray-200 mb-5">{tabs.filter(t => !t.hidden).map(t => (<button key={t.id} onClick={() => !t.disabled && setActiveTab(t.id)} className={`px-4 py-2.5 text-sm font-medium border-b-2 transition-colors ${activeTab === t.id ? "border-violet-600 text-gray-900" : t.disabled ? "border-transparent text-gray-300 cursor-not-allowed" : "border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300"}`}>{t.label}</button>))}</div>{activeTab === "overview" && <OverviewContent role={role} stepId={stepId} isReady={isReady} onSwitchTab={setActiveTab} />}{activeTab === "data" && <DataContent role={role} stepId={stepId} isReady={isReady} />}{activeTab === "logs" && <LogsContent role={role} stepId={stepId} />}</div>);
}

function HeroBar({ phase }) {
  const s = SESSION; const phaseLabel = phase === "prepare" ? "Prepare" : "Capture"; const phaseCls = phase === "prepare" ? "bg-blue-50 border-blue-200 text-blue-700" : "bg-violet-50 border-violet-200 text-violet-700"; const metrics = phase === "prepare" ? `${s.coworkers} coworkers · ${s.questions} questions · ${s.gaps} gaps` : `${s.answered} of ${s.questions} answered · ${s.satisfied} satisfied · ${s.gaps - s.gapsAddressed} gaps open`;
  return (<div className="rounded-lg border border-gray-200 bg-white p-4 mb-5 flex items-center gap-4"><div className="w-12 h-12 rounded-full bg-violet-100 text-violet-700 text-sm font-semibold inline-flex items-center justify-center shrink-0">{s.initials}</div><div className="flex-1 min-w-0"><div className="flex items-center gap-2 mb-0.5"><h1 className="text-lg font-semibold text-gray-900">{s.name}&apos;s session</h1><span className={`text-[9px] px-2 py-0.5 rounded uppercase tracking-wider font-semibold border ${phaseCls}`}>{phaseLabel}</span></div><p className="text-[12px] text-gray-500">{s.role} · {s.dept}</p><p className="text-[11px] text-gray-500 mt-0.5" style={{ fontFamily: "ui-monospace, Menlo, monospace" }}>{s.daysLeft} days left · Deadline {s.deadline} · {metrics}</p></div></div>);
}

function OverviewContent({ role, stepId, isReady, onSwitchTab }) { if (role === "offboarder") return <OffboarderOverview stepId={stepId} />; if (role === "coworker") return <CoworkerOverview stepId={stepId} isReady={isReady} onSwitchTab={onSwitchTab} />; return <ManagerOverview stepId={stepId} isReady={isReady} onSwitchTab={onSwitchTab} />; }

function ManagerOverview({ stepId, isReady, onSwitchTab }) {
  const s = SESSION;
  if (!isReady) return (<div className="rounded-lg border border-gray-200 bg-white p-6 text-center"><div className="w-10 h-10 rounded-full bg-violet-50 inline-flex items-center justify-center mb-3 mx-auto"><div className="w-4 h-4 rounded-full border-2 border-gray-300 border-t-violet-500 animate-spin" /></div><h3 className="text-sm font-medium text-gray-900 mb-1">Collecting data from {s.boards} boards...</h3><p className="text-xs text-gray-500">We&apos;ll notify you when ready.</p></div>);
  if (stepId === "capture") return (<div className="space-y-4"><div className="rounded-lg border border-gray-200 bg-white p-5"><h3 className="text-sm font-semibold text-gray-900 mb-3">Capture in progress</h3><div className="flex items-center gap-3 mb-1"><div className="flex-1 h-[6px] rounded-full bg-gray-200 overflow-hidden"><div className="h-full rounded-full bg-violet-500" style={{ width: `${Math.round(s.answered/s.questions*100)}%` }} /></div><span className="text-[11px] text-gray-700 font-medium" style={{ fontFamily: "ui-monospace, Menlo, monospace" }}>{s.answered}/{s.questions}</span></div><p className="text-[11px] text-gray-500 mb-4">{s.questions - s.answered} questions remaining</p><div className="grid grid-cols-3 gap-3"><MetricCard label="Satisfied" value={s.satisfied} /><MetricCard label="Waiting review" value={s.answered - s.satisfied} /><MetricCard label="Gaps addressed" value={`${s.gapsAddressed}/${s.gaps}`} /></div><p className="text-[11px] text-gray-500 mt-3" style={{ fontFamily: "ui-monospace, Menlo, monospace" }}>Started 3 days ago · {s.daysLeft} days left</p></div><div className="flex items-center gap-3"><button onClick={() => onSwitchTab("data")} className="h-9 px-4 rounded-lg border border-gray-300 text-sm font-medium text-gray-700 hover:bg-gray-50">Review in Data tab</button><button className="h-9 px-4 rounded-lg bg-violet-600 hover:bg-violet-700 text-white text-sm font-medium inline-flex items-center gap-2">Move to Deliver<ArrowRight className="w-3.5 h-3.5" /></button></div><p className="text-[10px] text-gray-400">{s.answered}/{s.questions} answered · {s.satisfied} satisfied · {s.gaps - s.gapsAddressed} gaps left</p></div>);
  return (<div className="space-y-4"><div className="rounded-lg border border-gray-200 bg-white p-5"><h3 className="text-sm font-semibold text-gray-900 mb-3">Data collection complete</h3><div className="grid grid-cols-4 gap-3 mb-4"><MetricCard label="Boards" value={s.boards} /><MetricCard label="Cards" value={s.cards} /><MetricCard label="Areas" value={s.modules} /><MetricCard label="Questions" value={s.questions} /></div><div className="pt-3 border-t border-gray-100 space-y-2"><p className="text-[10px] text-gray-500 uppercase tracking-wider font-medium">Knowledge areas</p><div className="flex flex-wrap gap-1.5">{["Payment Service", "CI/CD Pipeline", "Shared Libraries", "Monitoring & Alerts", "Infrastructure as Code"].map(m => (<span key={m} className="text-[11px] px-2 py-1 rounded-md bg-gray-50 border border-gray-200 text-gray-700">{m}</span>))}</div></div><div className="pt-3 mt-3 border-t border-gray-100 grid grid-cols-2 gap-3"><div><p className="text-[10px] text-gray-500 uppercase tracking-wider font-medium mb-1">Coworker engagement</p><p className="text-[12px] text-gray-700">2 of 3 have asked questions</p></div><div><p className="text-[10px] text-gray-500 uppercase tracking-wider font-medium mb-1">Knowledge gaps</p><p className="text-[12px] text-gray-700">6 gaps (3 card + 3 AI)</p></div></div></div><div className="flex items-center gap-3"><button onClick={() => onSwitchTab("data")} className="h-9 px-4 rounded-lg border border-gray-300 text-sm font-medium text-gray-700 hover:bg-gray-50">Review in Data tab</button><Link href="/session/minh-le" className="h-9 px-4 rounded-lg bg-violet-600 hover:bg-violet-700 text-white text-sm font-medium inline-flex items-center gap-2">Start Capture<ArrowRight className="w-3.5 h-3.5" /></Link></div></div>);
}

function OffboarderOverview({ stepId }) {
  const s = SESSION;
  if (stepId === "capture") return (<div className="rounded-lg border border-violet-200 bg-violet-50/30 p-5"><div className="flex items-center gap-2 mb-3"><Sparkles className="w-4 h-4 text-violet-600" /><h3 className="text-sm font-semibold text-gray-900">Your question queue</h3></div><div className="flex items-center gap-3 mb-1"><div className="flex-1 h-[6px] rounded-full bg-gray-200 overflow-hidden"><div className="h-full rounded-full bg-violet-500" style={{ width: `${Math.round(s.answered/s.questions*100)}%` }} /></div><span className="text-[11px] font-medium" style={{ fontFamily: "ui-monospace, Menlo, monospace" }}>{s.answered}/{s.questions}</span></div><p className="text-[12px] text-gray-500 mb-3">{s.questions - s.answered} remaining</p><Link href="/session/minh-le?tab=data" className="h-8 px-4 rounded-md bg-violet-600 hover:bg-violet-700 text-white text-xs font-medium inline-flex items-center gap-1.5">Open question queue<ArrowRight className="w-3 h-3" /></Link></div>);
  return (<div className="rounded-lg border border-dashed border-gray-300 bg-gray-50 p-8 text-center"><div className="w-12 h-12 rounded-full bg-gray-100 inline-flex items-center justify-center mb-3 mx-auto"><Clock className="w-5 h-5 text-gray-400" strokeWidth={1.5} /></div><h3 className="text-sm font-medium text-gray-700 mb-1">Your session is being prepared</h3><p className="text-xs text-gray-500">You&apos;ll be notified when ready.</p></div>);
}

function CoworkerOverview({ stepId, isReady, onSwitchTab }) {
  if (!isReady) return (<div className="rounded-lg border border-dashed border-gray-300 bg-gray-50 p-8 text-center"><div className="w-12 h-12 rounded-full bg-gray-100 inline-flex items-center justify-center mb-3 mx-auto"><Clock className="w-5 h-5 text-gray-400" strokeWidth={1.5} /></div><h3 className="text-sm font-medium text-gray-700 mb-1">Session is being set up</h3><p className="text-xs text-gray-500">You&apos;ll be notified when ready.</p></div>);
  if (stepId === "capture") return (<div className="space-y-4"><div className="rounded-lg border border-gray-200 bg-white p-5"><h3 className="text-sm font-semibold text-gray-900 mb-1">Your questions</h3><p className="text-[12px] text-gray-500 mb-3">Review answers and ask follow-ups.</p><div className="grid grid-cols-3 gap-3"><MetricCard label="Answered" value={2} /><MetricCard label="Waiting" value={1} /><MetricCard label="Satisfied" value={1} /></div><p className="text-[11px] text-yellow-700 mt-3 flex items-center gap-1.5"><AlertTriangle className="w-3 h-3" />1 answer waiting for review</p></div><button onClick={() => onSwitchTab("data")} className="h-9 px-4 rounded-lg bg-violet-600 hover:bg-violet-700 text-white text-sm font-medium inline-flex items-center gap-2">Review in Data tab<ArrowRight className="w-3.5 h-3.5" /></button></div>);
  return (<div className="space-y-4"><div className="rounded-lg border border-gray-200 bg-white p-5"><h3 className="text-sm font-semibold text-gray-900 mb-1">Minh Lê is leaving soon</h3><p className="text-[12px] text-gray-500 mb-3">Senior Backend Engineer · Last day July 4, 2026</p><div className="pt-3 border-t border-gray-100 space-y-2"><p className="text-[10px] text-gray-500 uppercase tracking-wider font-medium">Knowledge areas</p><div className="flex flex-wrap gap-1.5">{["Payment Service", "CI/CD Pipeline", "Shared Libraries", "Monitoring & Alerts", "Infrastructure as Code"].map(m => (<span key={m} className="text-[11px] px-2 py-1 rounded-md bg-gray-50 border border-gray-200 text-gray-700">{m}</span>))}</div></div><div className="pt-3 mt-3 border-t border-gray-100 grid grid-cols-2 gap-3"><div><p className="text-[10px] text-gray-500 uppercase tracking-wider font-medium mb-1">Your activity</p><p className="text-[12px] text-gray-700">0 questions asked</p></div><div><p className="text-[10px] text-gray-500 uppercase tracking-wider font-medium mb-1">Others</p><p className="text-[12px] text-gray-700">2 coworkers active</p></div></div></div><button onClick={() => onSwitchTab("data")} className="h-9 px-4 rounded-lg bg-violet-600 hover:bg-violet-700 text-white text-sm font-medium inline-flex items-center gap-2">Browse Data tab<ArrowRight className="w-3.5 h-3.5" /></button></div>);
}

function DataContent({ role, stepId, isReady }) {
  const [selectedCard, setSelectedCard] = useState(null); const isCapture = stepId === "capture";
  if (role === "offboarder" && !isCapture) return (<div className="rounded-lg border border-dashed border-gray-300 bg-gray-50 p-8 text-center"><h3 className="text-sm font-medium text-gray-700 mb-1">Questions are being collected</h3><p className="text-xs text-gray-500">You&apos;ll see them when Capture starts.</p></div>);
  if (!isReady) return (<div className="rounded-lg border border-dashed border-gray-300 bg-gray-50 p-8 text-center"><div className="w-10 h-10 rounded-full bg-violet-50 inline-flex items-center justify-center mb-3 mx-auto"><div className="w-4 h-4 rounded-full border-2 border-gray-300 border-t-violet-500 animate-spin" /></div><h3 className="text-sm font-medium text-gray-700 mb-1">Data is being collected...</h3><p className="text-xs text-gray-500">Accordion appears when crawl finishes.</p></div>);
  return (<div className="relative"><div>
    <div className="mb-4 flex items-center gap-2"><input placeholder="Ask a general question..." className="flex-1 h-9 px-3 rounded-lg border border-gray-200 text-sm focus:outline-none focus:ring-2 focus:ring-violet-500/20 focus:border-violet-400" /><button className="h-9 px-3 rounded-lg bg-violet-600 hover:bg-violet-700 text-white text-xs font-medium">Ask</button></div>
    {GENERAL_QUESTIONS.length > 0 && (<div className="rounded-lg border border-violet-200 bg-violet-50/20 mb-3 overflow-hidden"><div className="px-4 py-2.5 bg-violet-50/40 border-b border-violet-200 flex items-center gap-2"><MessageCircle className="w-3.5 h-3.5 text-violet-500" /><span className="text-sm font-semibold text-gray-900">General questions</span><span className="text-[11px] text-gray-500">{GENERAL_QUESTIONS.length}</span></div>{GENERAL_QUESTIONS.map((q, i) => (<div key={i} className="px-4 py-2.5 border-b border-violet-100 last:border-b-0"><div className="text-[12px] text-gray-900">{q.q}</div><div className="text-[10px] text-gray-500 flex items-center gap-1 mt-0.5"><User className="w-2.5 h-2.5" />{q.from}</div>{isCapture && q.answer && <AnswerBlock q={q} role={role} />}{isCapture && !q.answer && role === "offboarder" && (<div className="mt-2"><textarea placeholder="Type your answer..." className="w-full h-16 px-2 py-1.5 rounded border border-gray-200 text-[11px] resize-none focus:outline-none focus:ring-2 focus:ring-violet-500/20" /><div className="flex items-center justify-between mt-1"><button className="text-[10px] text-gray-500 inline-flex items-center gap-1 hover:text-violet-600"><Paperclip className="w-2.5 h-2.5" />Attach file</button><button className="h-6 px-2 rounded bg-violet-600 text-white text-[10px]">Submit</button></div></div>)}</div>))}</div>)}
    {MODULES_DATA.map((board, bi) => (<div key={bi} className="rounded-lg border border-gray-200 bg-white mb-3 overflow-hidden"><div className="px-4 py-2.5 bg-gray-50 border-b border-gray-200 flex items-center gap-2"><Layers className="w-3.5 h-3.5 text-gray-400" /><span className="text-sm font-semibold text-gray-900">{board.board}</span><span className="text-[11px] text-gray-500">{board.boardCards} cards</span></div>{board.modules.map((mod, mi) => (<ModuleSection key={mi} mod={mod} role={role} isCapture={isCapture} selectedCard={selectedCard} onSelectCard={setSelectedCard} />))}</div>))}
  </div>{selectedCard && <><div className="fixed inset-0 bg-black/10 z-30" onClick={() => setSelectedCard(null)} /><div className="fixed top-0 right-0 h-full w-[480px] bg-white border-l border-gray-200 shadow-xl z-40 overflow-y-auto"><SidePanel card={selectedCard} role={role} onClose={() => setSelectedCard(null)} isCapture={isCapture} /></div></>}</div>);
}

function ModuleSection({ mod, role, isCapture, selectedCard, onSelectCard }) {
  const [expanded, setExpanded] = useState(true); const [showModQ, setShowModQ] = useState(false); const prog = modProgress(mod); const totalGaps = mod.gaps + (mod.moduleGaps || []).length;
  return (<div className="border-b border-gray-100 last:border-b-0">
    <button onClick={() => setExpanded(!expanded)} className="w-full px-4 py-2 flex items-center justify-between text-left hover:bg-gray-50"><div className="flex items-center gap-2"><ChevronDown className={`w-3 h-3 text-gray-400 transition-transform ${expanded ? "" : "-rotate-90"}`} /><span className="text-[13px] font-medium text-gray-900">{mod.name}</span><span className="text-[11px] text-gray-500">{mod.cards} cards</span>{mod.qs > 0 && <span className="text-[9px] px-1.5 py-0.5 rounded bg-violet-50 text-violet-600 border border-violet-200">{mod.qs} Qs</span>}{totalGaps > 0 && <span className="text-[9px] px-1.5 py-0.5 rounded bg-yellow-50 text-yellow-700 border border-yellow-200">{totalGaps} gap{totalGaps > 1 ? "s" : ""}</span>}{isCapture && prog.total > 0 && <span className={`text-[9px] px-1.5 py-0.5 rounded border ${prog.answered === prog.total ? "bg-emerald-50 text-emerald-700 border-emerald-200" : "bg-gray-50 text-gray-600 border-gray-200"}`}>{prog.answered}/{prog.total}</span>}</div>{role === "manager" && <span className="flex items-center gap-2 text-[10px] text-gray-400"><span className="hover:text-violet-600 inline-flex items-center gap-0.5"><Upload className="w-2.5 h-2.5" />Upload</span><span className="hover:text-violet-600">Rename</span></span>}</button>
    {expanded && (<>
      {mod.moduleGaps && mod.moduleGaps.length > 0 && (<div className="px-4 py-2 pl-10 border-t border-gray-50 space-y-1">{mod.moduleGaps.map((g, gi) => (<div key={gi} className="text-[10px] text-yellow-800 bg-yellow-50 border border-yellow-200 rounded-md px-2.5 py-1.5 flex items-start gap-1.5"><Sparkles className="w-3 h-3 shrink-0 mt-0.5 text-yellow-600" />{g}</div>))}</div>)}
      {mod.items && mod.items.map((card, ci) => { const isSel = selectedCard?.name === card.name; const st = isCapture ? cardStatus(card) : null; return (<button key={ci} onClick={() => onSelectCard(card)} className={`w-full px-4 py-2 pl-10 flex items-center gap-2 text-left border-t border-gray-50 ${isSel ? "bg-violet-50 border-l-2 border-l-violet-500" : "hover:bg-gray-50"}`}>{isCapture && <span className="w-4 shrink-0 text-center">{st === "done" ? <CheckCircle2 className="w-3.5 h-3.5 text-emerald-500" /> : st === "pending" ? <span className="text-gray-400 text-[11px]">○</span> : <span className="text-gray-300 text-[11px]">—</span>}</span>}<FileText className="w-3 h-3 text-gray-400 shrink-0" /><span className="text-[12px] text-gray-800 flex-1">{card.name}</span>{card.files && card.files.length > 0 && <Paperclip className="w-2.5 h-2.5 text-gray-300" />}{card.gaps.length > 0 && <span className="text-[8px] px-1 py-0.5 rounded bg-yellow-50 text-yellow-700">gap</span>}{card.qs.length > 0 && <span className="text-[8px] px-1 py-0.5 rounded bg-violet-50 text-violet-600">{card.qs.length} Q</span>}</button>); })}
      {(!mod.items || mod.items.length === 0) && (<div className="px-4 py-2 pl-10 text-[11px] text-gray-400 border-t border-gray-50">{mod.cards} cards</div>)}
      {role !== "offboarder" && (<div className="px-4 py-1.5 pl-10 border-t border-gray-50"><button onClick={(e) => { e.stopPropagation(); setShowModQ(!showModQ); }} className="text-[10px] text-violet-600 inline-flex items-center gap-1 hover:text-violet-700"><Plus className="w-2.5 h-2.5" />Ask about this module</button>{showModQ && <div className="flex gap-1.5 mt-1.5"><input placeholder={`Question about ${mod.name}...`} className="flex-1 h-7 px-2 rounded border border-gray-200 text-[10px] focus:outline-none focus:ring-2 focus:ring-violet-500/20" /><button className="h-7 px-2 rounded bg-violet-600 text-white text-[9px]">Ask</button></div>}</div>)}
    </>)}
  </div>);
}

function AnswerBlock({ q, role }) {
  const [satisfied, setSatisfied] = useState(!!q.satisfiedBy); const [showFollowUp, setShowFollowUp] = useState(false);
  return (<div className="mt-2"><div className="rounded-md px-3 py-2 bg-gray-50 border-l-2 border-emerald-400"><p className="text-[10px] text-gray-500 mb-1">{q.answeredBy} · {q.answeredAt}</p><p className="text-[11px] text-gray-800 leading-relaxed">{q.answer}</p>{q.file && <p className="text-[10px] text-gray-500 mt-1.5 flex items-center gap-1"><Paperclip className="w-2.5 h-2.5" />{q.file.name} ({q.file.size})</p>}</div>{role !== "offboarder" && (<div className="mt-1.5">{satisfied ? (<p className="text-[10px] text-emerald-600 flex items-center gap-1"><CheckCircle2 className="w-3 h-3" />Satisfied by {q.satisfiedBy || "you"} · {q.satisfiedAt || "now"}</p>) : (<div className="flex items-center gap-2"><button onClick={() => setSatisfied(true)} className="h-6 px-2 rounded border border-emerald-300 text-emerald-700 text-[10px] inline-flex items-center gap-1 hover:bg-emerald-50"><CheckCircle2 className="w-2.5 h-2.5" />Mark satisfied</button><button onClick={() => setShowFollowUp(!showFollowUp)} className="h-6 px-2 rounded border border-gray-300 text-gray-600 text-[10px] inline-flex items-center gap-1 hover:bg-gray-50">Ask follow-up</button></div>)}{showFollowUp && <div className="flex gap-1.5 mt-1.5"><input placeholder="Follow-up question..." className="flex-1 h-7 px-2 rounded border border-gray-200 text-[10px] focus:outline-none focus:ring-2 focus:ring-violet-500/20" /><button className="h-7 px-2 rounded bg-violet-600 text-white text-[9px]">Ask</button></div>}</div>)}</div>);
}

function SidePanel({ card, role, onClose, isCapture }) {
  const [followUp, setFollowUp] = useState("");
  return (<div className="p-5">
    <div className="flex items-center justify-between mb-3"><h3 className="text-[15px] font-semibold text-gray-900">{card.name}</h3><button onClick={onClose} className="w-7 h-7 rounded-md hover:bg-gray-100 inline-flex items-center justify-center text-gray-400"><X className="w-4 h-4" /></button></div>
    <p className="text-[10px] text-gray-500 uppercase tracking-wider font-medium mt-3 mb-1 pt-2 border-t border-gray-100">Description</p><p className="text-[11px] text-gray-700 leading-relaxed mb-2">{card.desc}</p>
    {card.checklist.length > 0 && (<><p className="text-[10px] text-gray-500 uppercase tracking-wider font-medium mt-3 mb-1 pt-2 border-t border-gray-100">Checklist</p>{card.checklist.map((c, i) => (<div key={i} className="flex items-center gap-1.5 text-[11px] py-0.5">{c.done ? <CheckCircle2 className="w-3 h-3 text-emerald-500" /> : <div className="w-3 h-3 rounded border border-gray-300" />}<span className={c.done ? "text-gray-500 line-through" : "text-gray-700"}>{c.text}</span></div>))}</>)}
    {card.gaps.length > 0 && (<><p className="text-[10px] text-gray-500 uppercase tracking-wider font-medium mt-3 mb-1 pt-2 border-t border-gray-100">Gaps ({card.gaps.length})</p>{card.gaps.map((g, i) => (<div key={i} className="text-[10px] text-yellow-800 bg-yellow-50 border border-yellow-200 rounded-md px-2.5 py-1.5 mb-1"><div className="flex items-start gap-1.5"><AlertTriangle className="w-3 h-3 shrink-0 mt-0.5" />{g}</div>{card.gapQs && card.gapQs[i] && <p className="text-[9px] text-violet-600 mt-1 pl-4">Related Q: {card.gapQs[i]}</p>}</div>))}</>)}
    <p className="text-[10px] text-gray-500 uppercase tracking-wider font-medium mt-3 mb-1 pt-2 border-t border-gray-100">Files ({(card.files || []).length})</p>
    {(card.files || []).length > 0 ? (card.files || []).map((f, i) => (<div key={i} className="flex items-center gap-2 text-[11px] py-1.5 px-2.5 rounded-md bg-gray-50 mb-1"><Paperclip className="w-3 h-3 text-gray-400 shrink-0" /><span className="text-gray-800 flex-1">{f.name}</span><span className="text-[10px] text-gray-400">{f.size}</span></div>)) : <p className="text-[11px] text-gray-400 mb-1">No files yet</p>}
    {role !== "offboarder" && <button className="text-[10px] text-violet-600 inline-flex items-center gap-1 mt-1 hover:text-violet-700"><Upload className="w-2.5 h-2.5" />Upload file</button>}
    <p className="text-[10px] text-gray-500 uppercase tracking-wider font-medium mt-3 mb-1 pt-2 border-t border-gray-100">Questions ({card.qs.length})</p>
    {card.qs.length > 0 ? card.qs.map((q, i) => (<div key={i} className="text-[11px] bg-gray-50 rounded-md px-2.5 py-2 mb-1.5"><p className="text-gray-900 mb-0.5">{q.q}</p><p className="text-[10px] text-gray-500 flex items-center gap-1">{q.from === "AI-generated" ? <><Sparkles className="w-2.5 h-2.5 text-violet-500" />{q.from}</> : <><User className="w-2.5 h-2.5" />{q.from}</>}</p>{isCapture && q.answer && <AnswerBlock q={q} role={role} />}{isCapture && !q.answer && role === "offboarder" && (<div className="mt-2 pt-2 border-t border-gray-200"><textarea placeholder="Type your answer..." className="w-full h-16 px-2 py-1.5 rounded border border-gray-200 text-[11px] resize-none focus:outline-none focus:ring-2 focus:ring-violet-500/20" /><div className="flex items-center justify-between mt-1"><button className="text-[10px] text-gray-500 inline-flex items-center gap-1 hover:text-violet-600"><Paperclip className="w-2.5 h-2.5" />Attach file</button><button className="h-6 px-2 rounded bg-violet-600 text-white text-[10px]">Submit</button></div></div>)}</div>)) : <p className="text-[11px] text-gray-400 mb-1">No questions yet</p>}
    {role !== "offboarder" && (<><p className="text-[10px] text-gray-500 uppercase tracking-wider font-medium mt-3 mb-1 pt-2 border-t border-gray-100">Ask a question</p><div className="flex gap-1.5"><input value={followUp} onChange={e => setFollowUp(e.target.value)} placeholder="Your question..." className="flex-1 h-8 px-2.5 rounded-md border border-gray-200 text-[11px] focus:outline-none focus:ring-2 focus:ring-violet-500/20" /><button className="h-8 px-2.5 rounded-md bg-violet-600 text-white text-[10px] font-medium">Ask</button></div></>)}
  </div>);
}

function LogsContent({ role, stepId }) {
  if (stepId === "collecting" || (role === "offboarder" && stepId !== "capture")) return <div className="text-center py-8 text-sm text-gray-500">No activity yet</div>;
  const captureLogs = [{ ts: "2:15 PM", type: "questions", text: "Minh Lê answered about token refresh" },{ ts: "1:40 PM", type: "questions", text: "Coworker A marked satisfied: webhook events" },{ ts: "1:20 PM", type: "files", text: "Minh Lê attached dlq-replay-runbook.pdf" },{ ts: "12:50 PM", type: "questions", text: "Minh Lê answered about retry logic" },{ ts: "12:30 PM", type: "questions", text: "Hà Vy asked follow-up on DLQ monitoring" },{ ts: "11:05 AM", type: "system", text: "Capture started — Minh Lê notified" },{ ts: "10:32 AM", type: "system", text: "Crawl complete — 64 cards, 5 modules" },{ ts: "10:24 AM", type: "system", text: "Session created by Hà Vy" }];
  const prepareLogs = [{ ts: "10:45 AM", type: "questions", text: "Coworker asked about customer escalations" },{ ts: "10:40 AM", type: "questions", text: "Hà Vy asked about Atlas rollback" },{ ts: "10:32 AM", type: "system", text: "Crawl complete — 64 cards, 5 modules" },{ ts: "10:24 AM", type: "system", text: "Session created by Hà Vy" }];
  const logs = stepId === "capture" ? captureLogs : prepareLogs;
  return (<div className="space-y-1.5"><div className="flex gap-2 mb-3">{["All", "System", "Questions", "Files", "Edits"].map(f => (<button key={f} className={`px-2.5 py-1 rounded-md text-[11px] ${f === "All" ? "bg-violet-50 text-violet-700 font-medium" : "text-gray-500 hover:bg-gray-100"}`}>{f}</button>))}</div>{logs.map((l, i) => { const border = l.type === "system" ? "rgb(229,231,235)" : l.type === "questions" ? "rgb(124,58,237)" : "rgb(234,179,8)"; return (<div key={i} className="flex items-start gap-3 px-3 py-2 rounded-md border border-gray-200 bg-white" style={{ borderLeft: `2px solid ${border}` }}><span className="text-[10px] text-gray-500 shrink-0 mt-0.5" style={{ fontFamily: "ui-monospace, Menlo, monospace" }}>{l.ts}</span><span className={`text-[9px] px-1.5 py-0.5 rounded uppercase tracking-wider font-medium shrink-0 ${l.type === "questions" ? "bg-violet-50 text-violet-600" : l.type === "files" ? "bg-yellow-50 text-yellow-700" : "bg-gray-100 text-gray-500"}`}>{l.type}</span><span className="text-[11px] text-gray-900">{l.text}</span></div>); })}</div>);
}

function MetricCard({ label, value }) { return (<div className="rounded-md bg-gray-50 border border-gray-200 px-3 py-2"><div className="text-[9px] text-gray-500 uppercase tracking-wider font-medium">{label}</div><div className="text-lg font-semibold text-gray-900 mt-0.5" style={{ fontFamily: "ui-monospace, Menlo, monospace" }}>{value}</div></div>); }
function RoleTabBar({ role, onChange }) { return (<div className="bg-white border-b border-gray-200 px-5 overflow-x-auto"><div className="flex gap-0 min-w-0">{ROLES.map(r => (<button key={r.id} onClick={() => onChange(r.id)} className={`flex items-center gap-2 px-4 py-2.5 border-b-2 transition-colors shrink-0 focus:outline-none ${role === r.id ? "border-violet-600 text-gray-900" : "border-transparent text-gray-500 hover:text-gray-700"}`}><div className={`w-6 h-6 rounded-full text-[9px] font-semibold inline-flex items-center justify-center ${role === r.id ? "bg-violet-100 text-violet-700" : "bg-gray-100 text-gray-500"}`}>{r.icon}</div><div className="text-left"><div className="text-[12px] font-medium leading-tight">{r.label}</div><div className="text-[10px] text-gray-500 leading-tight">{r.sub}</div></div></button>))}</div></div>); }
function FlowBar({ step, stepIdx, onJump, roleLabel }) { return (<div className="bg-white border-b border-gray-200 px-5 py-2 flex items-center justify-between gap-4"><div className="min-w-0 flex-1"><div className="flex items-center gap-2 text-[11px] text-gray-500"><span className="uppercase tracking-wider font-semibold text-violet-700">{roleLabel}</span><span className="text-gray-300">·</span><span style={{ fontFamily: "ui-monospace, Menlo, monospace" }}>step {stepIdx + 1}/{FLOW.length}</span></div><h1 className="text-sm font-semibold text-gray-900 truncate mt-0.5">{step.label}</h1></div><div className="flex items-center gap-1 shrink-0">{FLOW.map((s, i) => (<button key={s.id} onClick={() => onJump(i)} title={s.label} className={`w-7 h-7 rounded-md border text-[11px] font-medium focus:outline-none focus:ring-2 focus:ring-violet-500/20 ${i === stepIdx ? "bg-violet-600 text-white border-violet-600" : "bg-white text-violet-700 border-violet-200 hover:border-violet-400"}`} style={{ fontFamily: "ui-monospace, Menlo, monospace" }}>{i + 1}</button>))}</div></div>); }
function TopBar() { return (<header className="bg-white border-b border-gray-200 px-5 py-2.5 flex items-center justify-between gap-4"><div className="flex items-center gap-2 shrink-0"><div className="w-1.5 h-1.5 bg-violet-500 rounded-full" /><span className="text-gray-900 font-semibold tracking-[0.18em] text-xs" style={{ fontFamily: "ui-monospace, Menlo, monospace" }}>ART-EEP</span></div><div className="flex items-center gap-3"><button className="h-8 w-8 rounded-md hover:bg-gray-100 inline-flex items-center justify-center text-gray-500 relative"><Bell className="w-3.5 h-3.5" strokeWidth={1.75} /><span className="absolute top-1 right-1 w-1.5 h-1.5 rounded-full bg-rose-500" /></button><div className="flex items-center gap-2 pl-2 border-l border-gray-200"><div className="w-7 h-7 rounded-full bg-violet-100 text-violet-700 text-[11px] font-semibold inline-flex items-center justify-center">HV</div><div className="text-[11px]"><div className="font-medium text-gray-900 leading-tight">Hà Vy</div><div className="text-gray-500 leading-tight">Manager</div></div></div></div></header>); }
function FooterNav({ stepIdx, total, onChange, trigger }) { const atFirst = stepIdx === 0, atLast = stepIdx === total - 1; return (<footer className="bg-white border-t border-gray-200 px-5 py-2.5 flex items-center justify-between sticky bottom-0 z-20"><button onClick={() => !atFirst && onChange(stepIdx - 1)} disabled={atFirst} className={`h-8 px-3 rounded-md text-sm font-medium inline-flex items-center gap-1.5 focus:outline-none focus:ring-2 focus:ring-violet-500/20 ${atFirst ? "text-gray-300 cursor-not-allowed" : "text-gray-700 hover:bg-gray-100"}`}><ChevronLeft className="w-3.5 h-3.5" />Prev</button><div className="hidden sm:block text-[11px] text-gray-500 max-w-md text-center truncate px-3">{trigger}</div><button onClick={() => !atLast && onChange(stepIdx + 1)} disabled={atLast} className={`h-8 px-3 rounded-md text-sm font-medium inline-flex items-center gap-1.5 focus:outline-none focus:ring-2 focus:ring-violet-500/30 ${atLast ? "bg-gray-100 text-gray-400 cursor-not-allowed" : "bg-violet-600 hover:bg-violet-700 text-white"}`}>Next<ChevronRight className="w-3.5 h-3.5" /></button></footer>); }
