"use client";
import React, { useState } from "react";
import Link from "next/link";
import { CheckCircle2, Clock, AlertTriangle, Sparkles, Database, ArrowLeftRight, Shield, PartyPopper, ArrowRight } from "lucide-react";

export function DeliverOverview({ role, onSwitchTab, S, MD, modProgress, MC, ProgressBar }) {
  const [showCommit, setShowCommit] = useState(false);
  const [showBack, setShowBack] = useState(false);
  if (role === "offboarder") return <div className="space-y-4"><div className="text-center py-4"><div className="w-12 h-12 rounded-full bg-violet-100 text-violet-700 text-sm font-semibold inline-flex items-center justify-center mx-auto mb-3">{S.initials}</div><h2 className="text-xl font-semibold">{"Thank you, "}<span className="text-violet-600">Minh</span>.</h2><p className="text-[12px] text-gray-500 max-w-xs mx-auto mt-2">{"Your contributions are captured. H\u00e0 Vy will review before committing to the Knowledge Graph."}</p></div><div className="rounded-lg border border-gray-200 bg-white p-4"><p className="text-[11px] font-medium mb-2">What you contributed</p><div className="grid grid-cols-3 gap-3"><MC l="Answered" v={S.answered}/><MC l="Files" v={1}/><MC l="Gaps addressed" v={S.gapsAddressed}/></div></div><div className="rounded-lg border border-gray-200 bg-white p-4"><p className="text-[11px] font-medium mb-2">What happens next</p><div className="space-y-2">{[{n:1,t:"H\u00e0 Vy reviews your contributions",d:"You\u2019ll get a copy of any follow-ups.",active:true},{n:2,t:"Knowledge Graph commit",d:"Your answers will be available to the team in the Knowledge Graph."}].map(s=><div key={s.n} className="flex gap-2.5 text-[11px]"><div className={`w-5 h-5 rounded-full text-[10px] font-medium flex items-center justify-center shrink-0 ${s.active?"bg-violet-100 text-violet-700":"bg-gray-100 text-gray-500"}`}>{s.n}</div><div><p className="font-medium">{s.t}</p><p className="text-gray-500 text-[10px]">{s.d}</p></div></div>)}</div></div></div>;
  if (role === "coworker") return <div className="rounded-lg border border-dashed border-gray-300 bg-gray-50 p-8 text-center"><div className="w-12 h-12 rounded-full bg-gray-100 inline-flex items-center justify-center mb-3 mx-auto"><Clock className="w-5 h-5 text-gray-400" strokeWidth={1.5}/></div><h3 className="text-sm font-medium text-gray-700 mb-1">Session is being finalized</h3><p className="text-xs text-gray-500 max-w-xs mx-auto">{"H\u00e0 Vy is reviewing contributions before committing to the Knowledge Graph."}</p></div>;
  return <div className="space-y-4"><div className="rounded-lg border border-gray-200 bg-white p-5"><h3 className="text-sm font-semibold text-gray-900 mb-3">Session readiness</h3><ProgressBar/><div className="grid grid-cols-4 gap-3 my-3"><MC l="Answered" v={S.answered}/><MC l="Satisfied" v={S.satisfied}/><MC l="Gaps" v={`${S.gapsAddressed}/${S.gaps}`}/><MC l="Files" v={S.files}/></div><div className="pt-3 border-t border-gray-100"><p className="text-[11px] font-medium mb-2">Per-module readiness</p>{MD.flatMap(b=>b.modules).map(m=>{const p=modProgress(m);const tg=m.gaps+(m.moduleGaps||[]).length;const ready=p.answered===p.total&&p.total>0;return <div key={m.name} className="flex items-center gap-2 py-1.5 border-t border-gray-50 text-[11px]"><span className="flex-1 text-gray-900">{m.name}</span><span className="text-gray-500" style={{fontFamily:"ui-monospace,Menlo,monospace"}}>{p.answered}/{p.total}</span><span className="text-gray-400 text-[10px]">{tg}{" gap"}{tg!==1?"s":""}</span>{ready?<span className="text-[9px] px-1.5 py-0.5 rounded bg-emerald-50 text-emerald-700 border border-emerald-200 inline-flex items-center gap-0.5"><CheckCircle2 className="w-2.5 h-2.5"/>Ready</span>:<span className="text-[9px] px-1.5 py-0.5 rounded bg-yellow-50 text-yellow-700 border border-yellow-200 inline-flex items-center gap-0.5"><AlertTriangle className="w-2.5 h-2.5"/>{p.total-p.answered} unanswered</span>}</div>})}</div>{S.questions-S.answered>0&&<div className="mt-3 text-[10px] text-yellow-800 bg-yellow-50 border border-yellow-200 rounded-md px-3 py-2 flex items-center gap-1.5"><AlertTriangle className="w-3 h-3 shrink-0"/>{S.questions-S.answered}{" questions unanswered \u2014 they will not be committed."}</div>}</div><div className="flex items-center gap-3"><button onClick={()=>setShowBack(true)} className="h-9 px-4 rounded-lg border border-gray-300 text-sm font-medium text-gray-700 hover:bg-gray-50 inline-flex items-center gap-1.5"><ArrowLeftRight className="w-3.5 h-3.5"/>Back to Capture</button><button onClick={()=>setShowCommit(true)} className="h-9 px-4 rounded-lg bg-violet-600 hover:bg-violet-700 text-white text-sm font-medium inline-flex items-center gap-2"><Database className="w-3.5 h-3.5"/>Commit to Knowledge Graph</button></div>{showCommit&&<CommitModal S={S} onClose={()=>setShowCommit(false)}/>}{showBack&&<BackModal onClose={()=>setShowBack(false)}/>}</div>;
}

export function CompleteOverview({ role, S, MC }) {
  if (role === "offboarder") return <div className="text-center py-6"><div className="w-14 h-14 rounded-full bg-emerald-100 inline-flex items-center justify-center mb-3 mx-auto"><PartyPopper className="w-6 h-6 text-emerald-600"/></div><h2 className="text-lg font-semibold mb-1">Your knowledge has been committed.</h2><p className="text-[12px] text-gray-500 max-w-xs mx-auto">{S.answered}{" answers and "}{S.files}{" files are now in the Knowledge Graph. Your team can now access your knowledge."}</p><div className="grid grid-cols-3 gap-3 max-w-sm mx-auto mt-4"><MC l="Answers" v={S.answered}/><MC l="Files" v={1}/><MC l="Gaps resolved" v={S.gapsAddressed}/></div></div>;
  if (role === "coworker") return <div className="rounded-lg border border-emerald-200 bg-emerald-50/30 p-8 text-center"><div className="w-12 h-12 rounded-full bg-emerald-100 inline-flex items-center justify-center mb-3 mx-auto"><CheckCircle2 className="w-5 h-5 text-emerald-600"/></div><h3 className="text-sm font-medium text-gray-900 mb-1">Session complete</h3><p className="text-xs text-gray-500 max-w-xs mx-auto">{"Minh L\u00ea\u2019s knowledge is now in the Knowledge Graph. The answers you reviewed are available to the team."}</p></div>;
  return <div className="space-y-4"><div className="rounded-md bg-emerald-50 border border-emerald-200 p-3 flex items-center gap-2"><CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0"/><div><p className="text-[12px] font-medium text-emerald-800">Committed to Knowledge Graph</p><p className="text-[10px] text-emerald-600" style={{fontFamily:"ui-monospace,Menlo,monospace"}}>{"Jun 14, 2026 at 3:42 PM \u00b7 487 entries"}</p></div></div><div className="rounded-lg border border-gray-200 bg-white p-5"><div className="grid grid-cols-4 gap-3"><MC l="Committed" v={S.answered}/><MC l="Files" v={S.files}/><MC l="Gaps resolved" v={S.gapsAddressed}/><MC l="Excluded" v={S.questions-S.answered}/></div><p className="text-[11px] text-gray-500 mt-3">{"Minh L\u00ea\u2019s knowledge is now available to the team in the Knowledge Graph."}</p><div className="flex gap-3 mt-3"><Link href={`/knowledge-graph?prompt=${S.id}`} className="h-8 px-3 rounded-md border border-violet-300 text-violet-700 text-xs font-medium inline-flex items-center gap-1.5 hover:bg-violet-50"><Sparkles className="w-3 h-3"/>Explore in Knowledge Graph</Link><Link href="/" className="h-8 px-3 rounded-md border border-gray-300 text-gray-700 text-xs font-medium inline-flex items-center gap-1.5 hover:bg-gray-50">Back to dashboard</Link></div></div></div>;
}

function CommitModal({ S, onClose }) {
  return <div className="fixed inset-0 bg-black/30 z-50 flex items-center justify-center" onClick={onClose}><div className="bg-white rounded-xl shadow-xl p-6 w-[400px] border border-gray-200" onClick={e=>e.stopPropagation()}><h3 className="text-base font-semibold mb-3">Commit to Knowledge Graph</h3><p className="text-[12px] text-gray-500 mb-2">{"You\u2019re about to commit:"}</p><div className="text-[12px] space-y-0.5 mb-3"><p>{"\u00b7 "}{S.answered}{" answers across "}{S.modules}{" knowledge areas"}</p><p>{"\u00b7 "}{S.files}{" files"}</p><p>{"\u00b7 "}{S.gapsAddressed}{" gaps resolved"}</p></div>{S.questions-S.answered>0&&<div className="text-[11px] text-yellow-800 bg-yellow-50 border border-yellow-200 rounded-md px-3 py-2 mb-2">{S.questions-S.answered}{" unanswered questions will be excluded."}</div>}<div className="text-[11px] text-emerald-800 bg-emerald-50 border border-emerald-200 rounded-md px-3 py-2 mb-3 flex items-start gap-1.5"><Shield className="w-3.5 h-3.5 shrink-0 mt-0.5"/><span>Pre-commit sanitization will run automatically. Sensitive content is redacted before anything reaches the graph.</span></div><p className="text-[10px] text-gray-400 mb-4">This action is permanent.</p><div className="flex gap-2 justify-end"><button onClick={onClose} className="h-8 px-3 rounded-md border border-gray-300 text-sm font-medium text-gray-700 hover:bg-gray-50">Cancel</button><button className="h-8 px-3 rounded-md bg-violet-600 text-white text-sm font-medium inline-flex items-center gap-1.5 hover:bg-violet-700"><Database className="w-3.5 h-3.5"/>Commit</button></div></div></div>;
}

function BackModal({ onClose }) {
  return <div className="fixed inset-0 bg-black/30 z-50 flex items-center justify-center" onClick={onClose}><div className="bg-white rounded-xl shadow-xl p-6 w-[380px] border border-gray-200" onClick={e=>e.stopPropagation()}><h3 className="text-base font-semibold mb-3">Reopen Capture?</h3><p className="text-[12px] text-gray-500 mb-2">{"This will reopen the session for Minh L\u00ea. He\u2019ll be notified that more input is needed."}</p><p className="text-[10px] text-gray-400 mb-4">You can move back to Deliver again when ready.</p><div className="flex gap-2 justify-end"><button onClick={onClose} className="h-8 px-3 rounded-md border border-gray-300 text-sm font-medium text-gray-700 hover:bg-gray-50">Cancel</button><button className="h-8 px-3 rounded-md bg-rose-50 border border-rose-300 text-rose-700 text-sm font-medium inline-flex items-center gap-1.5 hover:bg-rose-100"><ArrowLeftRight className="w-3.5 h-3.5"/>Reopen Capture</button></div></div></div>;
}
